playbooks/roles/dante/tasks/main.yml, playbooks/roles/dante/templates/danted.conf.j2
Ansible provides `ansible_default_ipv4.interface`, which may or may not
be eth0. For example, on OpenVZ hosts, this is usually venet0.
=> Don't hardcode eth0 in dante configuration

playbooks/roles/openvpn/defaults/main.yml, playbooks/roles/openvpn/vars/main.yml
Because of ansible's [variable precedence][], non-default variables can't be easily modified via config files. Because the OpenVPN crypto parameters might be something someone wants to modify, they should instead be set as default values.
[variable precedence]: http://docs.ansible.com/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
=> Make openvpn crypto parameters easier to modify

playbooks/roles/common/tasks/main.yml
Show show the warning when the OS is not Debian based OR not version 7.
=> Fixed logic in Debian 7 warning

playbooks/linode.yml
Tokyo availability is limited, Singapore was recently added and does not have these limitations
=> add Linode Singapore DC, replace Tokyo as default

playbooks/roles/streisand-mirror/tasks/stunnel.yml, playbooks/roles/streisand-mirror/vars/stunnel.yml
Michal Trojnara (the maintainer of stunnel) has graciously set up stable download locations that will always redirect to the latest installer and source code files. This will prevent things from breaking when new versions are released and will also obviate the need for manual updates to the `stunnel_version` variable in the `playbooks/roles/streisand-mirror/vars/stunnel.yml` file.
=> Use new stunnel download locations for simplified version updates.

playbooks/roles/openvpn/templates/client-common.j2
Adds in ping keepalives into OpenVPN Client common configuration, this causes keep alives to be sent, resolves #180 :)
=> Adding in Ping Keepalives to Servers Internal IP

ansible.cfg
As of version 1.9, the usage of hostfile is deprecated. The new usage is inventory. For more information, please see Ansible config documentation:
http://docs.ansible.com/ansible/intro_configuration.html#hostfile
This is a relatively minor fix that should be easily mergeable without further changes.
=> Updated deprecated usage of hostfile config value

playbooks/amazon.yml
AWS just add a new region `ap-northeast-2 (Seoul)`. Add it to the regions list and keep the default region
to Singapore.
=> Add new Seoul region for AWS playbook

playbooks/roles/shadowsocks/templates/instructions.md.j2
In the OS X portion of the Shadowsocks instructions, two references to 'taskbar’ are made, however, 'menu bar' is the correct usage. Both instances of the former term were replaced with the latter in order to reduce any ambiguity.
=> Fix Shadowsocks OS X instructions to use correct UI terminology

playbooks/roles/shadowsocks/templates/instructions.md.j2
Recent versions of the client has adopted Material Design, and this commit
updates the instructions to reflect the changes.
I've removed the part about the CHN routes, as it's no longer on by default.
Here is a screenshot of the new version:
=> Amend instructions for the Shadowsocks client on Android

playbooks/roles/genesis-amazon/tasks/main.yml
For EC2 instances with public IP addresses, it’s usually desirable to assign an Elastic IP to the instance to ensure that the public IP does not change.
Without an Elastic IP, the public IP address will change any time the instance is stopped or restarted. If the public IP of the instance changes, it will break all sorts of things.
This update will associate an Elastic IP address to the EC2 instance immediately after instance creation, and assigns the Elastic IP to the streisand_ipv4_address variable for use in the rest of the playbook.
=> Update genesis-amazon to use Elastic IP

playbooks/roles/common/files/50unattended-upgrades, playbooks/roles/nginx/tasks/main.yml, playbooks/roles/rc-local/tasks/main.yml, playbooks/roles/tor-bridge/tasks/main.yml
Unattended upgrades will auto-update: Tor, OpenVPN, shadowsocks-libev and nginx
unattended upgrades will explicitly auto-remove unused dependencies
Unattended upgrades will reboot the server at midnight (depending on where the server location timezone is)
Tor and Nginx deb repos re-configured to use https instead of http
rc.local mode using octet notation (0755 instead of 755)
unattended upgrades can be tested by executing the following command: unattended-upgrade --debug --dry-run
note: tried switching shadowsocks deb repo to https but got errors :(
Edit: OpenVPN repo also uses https, but was configured to do so in another PR I have made: PR  #322).
shadowsocks-libev using https in the deb repo resulted in the following error:
`
W: Failed to fetch …
=> Unattended upgrades

playbooks/roles/l2tp-ipsec/tasks/main.yml, playbooks/roles/l2tp-ipsec/vars/main.yml
Fixes issue #355. Installs python-pip and the necessary python modules to enable SNI support and access the server hosting Libreswan source code.
=> Fixes issue #355

playbooks/roles/streisand-mirror/vars/shadowsocks.yml
Latest versions as obtained from GitHub
Fixes #349  because it turns out v2.10.5 of the Android app has an integrated barcode scanner
=> Update Android and Windows Shadowsocks mirrors

README.md, playbooks/amazon.yml, playbooks/roles/ec2-security-group/tasks/main.yml
As mentioned in #311, L2TP/IPSec works without issue on AWS. This commit adds the `l2tp-ipsec` (and the associated security group roles) back into the Amazon playbook.
Edit: I'd imagine this can also be applied to GCE, I just haven't got around to it.
=> Add l2tp/ipsec to AWS builds

playbooks/amazon.yml, playbooks/roles/ec2-security-group/tasks/main.yml, playbooks/roles/genesis-amazon/tasks/main.yml
Allows the user to optionally provide VPC and Subnet IDs when creating
a Streisand server. These values are then passed when creating security
group rules and the EC2 instances later on in the build process.
=> [AWS] Add VPC support

playbooks/roles/genesis-amazon/tasks/main.yml
This task configures a CloudWatch metric alarm to trigger auto-recovery
if the host system is down for 2 minutes.
AWS (via CloudWatch) supports a feature known as auto-recovery, which
will respawn an instance on host system failure. The recovered instance
is identical to the original instance, including instance ID,
private/elastic IP addresses, and metadata.
Currently this feature is only available in the `us-east-1` region for
the C3, C4, M3, R3, and T2 instance types.
@jlund Sorry for all the PRs. I know it's a lot of work maintaining these things... I'd be happy to help in any way that I can.
=> [AWS] Add autorecover alarm

playbooks/amazon.yml, playbooks/roles/genesis-amazon/tasks/main.yml
Adding `ansible_user` and `ansible_become` as host variables with the
`add_host` module satisfy the login requirements which are needed for
connecting to EC2 instances, and allows us to include the main play
from streisand.yml.
=> Include streisand.yml in amazon.yml

README.md, playbooks/google.yml, playbooks/roles/gce-network/tasks/main.yml
Just as in #370, adding support for L2TP/IPsec, but for Google Compute Engine this time around.
Closes #311
=> Add l2tp/ipsec support to GCE builds

playbooks/roles/streisand-mirror/vars/openvpn.yml
updates OpenVPN to the latest 2.3.12 release for the local streisand-mirror
=> Update OpenVPN streisand-mirror

playbooks/roles/common/vars/main.yml
Ensures that apt-transport-https is installed as some cloud providers don't image their distros with it installed by default. Addresses #407
=> apt-transport-https

README.md, ansible.cfg, inventory, playbooks/streisand.yml
Also, moved the become directive to the playbook. While it should work
correctly from ansible.cfg, it didn't in my tests.
=> Document using ansible_user in inventory

playbooks/roles/shadowsocks/templates/instructions.md.j2, playbooks/roles/streisand-mirror/templates/mirror-index.md.j2, playbooks/roles/streisand-mirror/vars/shadowsocks.yml
OSX client ShadowsocksX-NG is now recommended on [shadowsocks.org](https://shadowsocks.org/en/download/clients.html).
However, [it require OSX 10.10+](https://github.com/shadowsocks/ShadowsocksX-NG/releases)
=> Add ShadowsocksX-NG to streisand-mirror

playbooks/roles/genesis-amazon/tasks/main.yml
EC2 auto-recovery is live in all AWS Regions, and now supports more instance types.
See https://aws.amazon.com/about-aws/whats-new/2016/05/amazon-ec2-auto-recovery-now-available-in-the-beijing-china-region/ for more info. It looks like this was available when I first introduced this PR in #374, but I just now noticed it's available in all regions.
=> Update AWS auto-recovery conditions

README.md
Similar to this commit for issue #203: https://github.com/jlund/streisand/commit/9709cd2e09966cf1cad3484bb4b66d18b274ed48
Error message:
```
TASK [genesis-linode : Create the server] **************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "pycurl required for this module"}
```
I'm on OS X v10.9.5.
=> `pycurl required for this module` error on OS X also

playbooks/roles/ec2-security-group/tasks/main.yml, playbooks/roles/gce-network/tasks/main.yml, playbooks/roles/l2tp-ipsec/defaults/main.yml
Hi @DavidWittman, I'm trying to implement what you proposed in #453, to collect variables into a centralized place. However, I found that variables defined in `roles/l2tp-ipsec/defaults/main.yml` are totally useless. They are not actually "variable" since we can't change them to other values, and they had already been hardcoded in many place.
Removing them can eliminate fews "undefined variable" errors. Otherwise, we have to move them to the centralized place, but I think it will mislead users that those ports are customizable.
=> Removed ike_port, ipsec_port and l2tp_port variables

playbooks/amazon.yml, playbooks/cloud-status.yml, playbooks/digitalocean.yml, playbooks/google.yml, playbooks/rackspace.yml
Ubuntu cloud-init allows the execution of post-deployment tasks. Cloud-init is used or supported by Ubuntu images on the following providers that Streisand uses: Amazon, DigitalOcean, Rackspace, and Google. Linode does not install cloud-init on its Ubuntu images by default.
After the SSH connection is established, but before any roles are installed, this patch checks for the /var/lib/cloud/instance/boot-finished file, indicating all tasks performed by cloud-init have been completed. The check occurs every second for 30 seconds. If the file is not found within the timeout period, a fail is thrown and the deployment stops.
Since cloud-init tasks can impact Streisand, waiting for its completion avoids race conditions.
Fixes #457
=> Added support for Ubuntu cloud-init status checking

inventory
Hi, 
As a OSX user having installed python without brew, I run into a ansible error:
`"msg": "boto required for this module"`
```
$- pip list boto | grep boto
boto (2.45.0)
```
I'm not familiar with ansible, but the osx/ansible community seams to have a semi-official workaround, described here: 
https://github.com/ansible/ansible/issues/15019
This pull request implement that workaround, if the inventory file should not change, that should be documented to point people in that direction. 
With the modification to inventory, I was able to spin up a server and connect to it. 
Thanks y'all for your work.
=> workaround for ec2+boto+osx user. 

playbooks/roles/genesis-amazon/tasks/main.yml, playbooks/roles/genesis-digitalocean/tasks/main.yml, playbooks/roles/genesis-google/tasks/main.yml, playbooks/roles/genesis-linode/tasks/main.yml, playbooks/roles/genesis-rackspace/tasks/main.yml
This is a proposed accommodation for issue #548. The fix takes place at the end of each `gensis-*` role where the `streisand_server_name` fact is being set for the remainder of the playbook's execution.
=> Ensure the `streisand_server_name` variable does not get set to a value with whitespace characters

playbooks/google.yml
Added support for the cheapest google cloud instance type.
It's 10$ cheaper than g1-small.
I've noticed no performance issues with one user.
=> Added support for f1-micro instance type in google cloud

playbooks/amazon.yml
This patch modifies `playbooks/amazon.yml` to support the [Canada (Central) AWS region](https://aws.amazon.com/about-aws/whats-new/2016/12/announcing-the-aws-canada-central-region/).
=> amazon playbook: support ca-central-1 region

playbooks/roles/ufw/tasks/main.yml
As a result of GFW DNS spoofing. Most Shadowsocks users in China need to relay their DNS request via ss-tunnel.
Shadowsocks-libev official repository [enable this feature by default](https://github.com/shadowsocks/shadowsocks-libev/blob/master/debian/shadowsocks-libev.default#L18) on server-side. I thinks it's better to let UFW open the udp port for Shadowsocks.
=> UFW: open udp port for Shadowsocks.

playbooks/roles/ssh/files/sshd_config
Happened to catch this as I was reading through the documentation :)
=> fix: Documentation mispelling

playbooks/roles/openconnect/templates/instructions.md.j2, playbooks/roles/streisand-mirror/vars/openconnect.yml
Updates OpenConnect GUI for Windows to v1.5.1
macOS portions were commented out due to an issue with the latest release that crashes on El Capitan, but can later be re-introduced easily once an new build is released.
Would appreciate a test on a Windows machine to verify that there are no issues.
Thanks!
=> Update openconnect gui for windows

playbooks/roles/l2tp-ipsec/vars/main.yml
Closes #589 
Tested on DO droplet on macOS El-Capitan with native l2tp/ipsec client, no issues.
=> Updated Libreswan to 3.20

monkey/usercustomize.py, streisand
Only in the next ansible version will we have support for setting Linode's kernels directly from our playbooks. Until then, we need to monkey patch around this limitation.
Fixes: #500
Fixes: #609
=> linode: work around kernel limitation

inventory, playbooks/roles/genesis-linode/tasks/main.yml
The use of ansible_python_interpreter isn't correct, because the given
python will not work on both version of python, so it breaks entirely,
on many distros unless a user manually edits inventory. Since Streisand
is mostly used by clueless users, this probably isn't a good situation.
Rather than fixing this problem, it occurs to me that elsewhere distro
ID constants are being hard coded (for, say, GRUB 2). Since Linode isn't
changing the IDs returned from their API anyway, it's much easier just
to hard code this. When we change distros, we'll change IDs.
This is much simpler and less error prone. I don't think we gained
anything from the prior abstraction anyway.
=> linode: hard code distro id

.gitignore, playbooks/roles/wireguard/tasks/main.yml
An improvement on #615, this is necessary for providers like Linode and possibly others.
This hasn't actually been tested, so please somebody run it at least once before merging.
=> wireguard: explicitly install kernel headers for running kernel

inventory
In 89f40e8 we revoved the `ansible_python_interpreter` on the assumption
it broke for many distros unless modified. This is likely still true,
but removing it also breaks OSX hosts that were previously working.
41f4f87 restores the `ansible_python_interpreter` var until a less
jarring fix can be worked out.
=> Restore `ansible_python_interpreter` inv var.

playbooks/roles/wireguard/tasks/main.yml
After rebooting, we probably want to have the newer kernel headers available too.
=> wireguard: always add generic headers

playbooks/roles/genesis-linode/defaults/main.yml, playbooks/roles/genesis-linode/tasks/main.yml
=> linode: abstract out the distribution id

playbooks/roles/l2tp-ipsec/tasks/main.yml
This mitigates sporadic "Hostname mismatch" errors on the official download location that appear to be related to SNI.
=> Retrieve the Libreswan source code from a CloudFront mirror location.

playbooks/roles/wireguard/templates/wg0-client.conf.j2, playbooks/roles/wireguard/templates/wg0-server.conf.j2
This is needed for some strange providers who give non-standard MTUs.
This is fairly rare on the client side, but on the server side, Google
Cloud Platform gives 1460, presumably due to vxlan or some other SDN
they deploy.
Also, while we're at it, since Streisand doesn't support IPv6 at the
moment (even though WireGuard does), we can get an extra 20 bytes in our
MTU by subtracting 60 instead of 80.
**I haven't tested this commit, so please make sure this actually works before merging.**
=> wireguard: automatically set MTU from default route

README.md
Homebrew auto-updates on `brew install` now, and this change has had about a year to propagate.
https://github.com/Homebrew/brew/pull/679
=> Remove explicit `brew update`

playbooks/roles/shadowsocks/vars/main.yml
7019b4b upgrades shadowsocks-libev from 3.0.5 to 3.0.6. Most notably
this version fixes an AEAD related bug affecting the latest shadowrocket
iOS app.
Resolves #650
=> Upgrade shadowsocks-libev to 3.0.6.

streisand
Having discussed this with other maintainers it sounds like bumping the REQUIRED_ANSIBLE_VERSION that the streisand wrapper checks is fairly painless since its generally easy for folks to update their Ansible installs to the latest via pip/etc.
With that in mind this PR bumps the REQUIRED_ANSIBLE_VERSION to 2.3.0.0 ahead of using some of the features it provides. It seems prudent to keep this process fluid by doing it frequently.
=> Updates REQUIRED_ANSIBLE_VERSION to 2.3.0.0

playbooks/roles/shadowsocks/templates/instructions.md.j2
New versions of Potatso 2 now support AEAD ciphers.
=> Update the Shadowsocks instructions to remove the Potatso AEAD warning.

playbooks/roles/streisand-mirror/vars/shadowsocks.yml
815b8b6 updates the Streisand mirror copy of the Shadowsocks Android APK to version 4.1.7, the latest release at the time of writing.
Resolves https://github.com/jlund/streisand/issues/678
I tested this end-to-end with a fresh Linode instance and an Android 7.1.2 device using the mirrored APK.
=> Updates shadowsocks android client mirror to 4.1.7.

playbooks/digitalocean.yml, playbooks/roles/genesis-digitalocean/tasks/main.yml
When running streisand this morning, I noticed that it did not work with Digital Ocean.  Upon running the breaking playbook with -vvv, I saw the following error:
```
fatal: [localhost]: FAILED! => {
"changed": false,
"failed": true,
"invocation": {
"module_args": {
"api_token": "",
"backups_enabled": false,
"command": "ssh",
"id": null,
"image_id": null,
"ipv6": false,
"name": "streisand",
"private_networking": false,
"region_id": null,
"size_id": null,
"ssh_key_ids": null,
"ssh_pub_key": "<JUST MY PUBKEY>",
"state": "present",
"unique_name": false,
"user_data": null,
"virtio": true,
"wait": true,
"wait_timeout": 300
}
},
"msg": "Unable to load DO_API_TOKEN"
}
```
The messaging and expected env vars in master both refer to DIGITALOCEAN_API_TOKEN, so I changed the messaging and the name of …
=> changes playbooks to use/modify DO_API_TOKEN

playbooks/roles/wireguard/templates/wg0-client.conf.j2, playbooks/roles/wireguard/templates/wg0-server.conf.j2
The latest wg-quick does this part automatically, so we no longer need this.
This reverts commit 945f9b0f057211d64cdc725ef1b55bc98ba9ffa1.
Please merge this after EggieCode/wireguard-ppa#18 is closed.
=> wg-quick now figures out MTU on its own

playbooks/group_vars/all, tests/group_vars/all/all
Fixes the conditional check in the block that opens the instructions when setup is finished.
=> Set the streisand_noninteractive variable outside of Vagrant too.

playbooks/roles/l2tp-ipsec/templates/ipsec.conf.j2
The builtin vpn on iOS didn't play well with the settings in the
l2tp playbook. This adds a couple settings to make that happen.
=> tweaks the l2tp settings to work with iOS

playbooks/roles/wireguard/templates/wg0-client.conf.j2, playbooks/roles/wireguard/templates/wg0-server.conf.j2
This brings the client and server config files into alignment with the protocol changes and improvements that were made in the latest WireGuard snapshot (0.0.20170517):
https://lists.zx2c4.com/pipermail/wireguard/2017-May/001334.html
=> WireGuard - Move the pre-shared key field to the Peer section.

README.md, playbooks/roles/wireguard/tasks/main.yml, playbooks/roles/wireguard/templates/wg0-client.conf.j2, playbooks/roles/wireguard/templates/wg0-server.conf.j2, playbooks/roles/wireguard/vars/main.yml
Since Streisand is deployed over the internet through a non PQ-secure
mechanism, the preshared key mechanism isn't really useful, so just
don't configure it.
=> wireguard: preshared keys aren't useful here

playbooks/roles/streisand-mirror/vars/openvpn.yml
Previous version is unavailable for download.
Resolves  #694.
=> Update Tunnelblick to 3.7.1a

playbooks/roles/tor-bridge/defaults/main.yml, playbooks/roles/tor-bridge/templates/torrc.j2
This PR obsoletes https://github.com/jlund/streisand/pull/647 by completing the remaining review feedback required for merge.
The original PR description said:
> In this case "private" means that the bridge is configured with the option PublishServerDescriptor 0. Without this option set, The Tor Project can learn about the bridge and may distribute its address to others.
https://www.whonix.org/wiki/Bridges#Additional_Information_and_Recommendations
User's that wish to publish their tor-bridge can uncomment the `tor_publish_service_desc: "bridge"` line from the torrc.j2 config template.
A follow-up task is to implement https://github.com/jlund/streisand/issues/655 and allow prompting for the value of this setting.
Thanks to @amsqube for the initial implementation in #647 :cake: :tada: …
=> Default tor-bridge torrjc PublishServerDescriptor config to "0".

playbooks/roles/wireguard/templates/wg0-client.conf.j2
This patch is untested, and won't really be easily testable until
EggieCode/wireguard-ppa#20 is merged and uploaded. However, without
testing, several observations struck me:
- resolvconf doesn't need real interface names. A bogus name will work
just fine.
- Prefixing an arbitrary name with 'tun' moves it to the top-ish of the
list.
- Debian's resolvconf ignores arguments after the first, so we can still
continue to supply the openresolv flags for implementations that
support it.
Thus, we give resolvconf tun.%i, and this should work good enough. There
are a few limitations, however:
- The DNS server is not _exclusive_, which means that if it doesn't
reply in time, the resolver might choose to try other servers. This is
a security feature limitation of Debian's resolvconf. Not our problem, …
=> resolvconf: support Debian's broken resolvconf

playbooks/roles/shadowsocks/templates/config.json.j2
This reverts commit 282d5eac6b12d33c89a434d0042c2e2b646b61d8
from https://github.com/jlund/streisand/pull/707.
It causes issues on AWS from the I think the primary interface address
having an internal 10.x VPC IP that doesn't match the external IP.
=> Revert "shadowsocks: listen on streisand_ipv4_address (#707)"

README.md
The README has a feature line describing the Streisand server's logging
configuration w.r.t. trying to minimize client IP collection. My
understanding of the original intent was that this was considered from
the perspective of one sysadmin running a Streisand instance for many
clients, whose IPs would be ideally not recorded. This has caused some
some confusion[0] for folks thinking it was about the sysadmin/operator
themselves.
Overall I think this conversation requires a deeper conversation RE:
threat models and we should probably stay out of the weeds by saying
less in the README :-)
[0]: https://arstechnica.com/gadgets/2017/05/how-to-build-your-own-vpn-if-youre-rightfully-wary-of-commercial-options/?comments=1&post=33391773
=> Removes README claim RE: client IP logging.

CONTRIBUTING.md, ISSUE_TEMPLATE.md
This adds a CONTRIBTUING.md and ISSUE_TEMPLATE.md to give guidance on where to submit different types of issues.  Much thanks to https://github.com/Microsoft/vscode/ for the heavy inspiration.
=> added templates, partial fix of #656

playbooks/roles/streisand-mirror/vars/shadowsocks.yml
The Shadowsocks Windows GUI client has [posted a 4.0.4 release](https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.0.4). This
commit updates the Streisand mirror metadata to mirror this new release
instead of the outdated 4.0.1 release.
=> Updates mirrored Shadowsocks Windows client to 4.0.4.

playbooks/roles/streisand-mirror/vars/shadowsocks.yml
The `shadowsocks-android` project has tagged a `4.1.8` release today
that reintroduces the built-in QR code scanner. Some Streisand users
have found this feature helpful in the event they don't have the ZXing
QR code scanner and can't access Google Play to get it.
This commit updates the Streisand mirror's copy of the Shadowsocks
Android client to version 4.1.8.
Resolves https://github.com/jlund/streisand/issues/349
=> Update mirrored Shadowsocks Android APK to 4.1.8.

playbooks/roles/ssh/templates/instructions-fr.md.j2
It looks like the `shadowsocks_local_port` snuck into the French SSH
instructions template where it should be `ssh_default_socks_port`. This
commit fixes that error.
=> Remove shadowsocks port from FR SSH docs.

playbooks/provider-detect.yml
Some providers (e.g. Scaleway) do not include `dmidecode` in the base
Ubuntu 16.04 image so we must explicitly request it be installed before
trying to use it for provider detection.
Thanks to @dmitry-kulikov for reporting. Resolves https://github.com/jlund/streisand/issues/738
=> Require `dmidecode` package presence for provider-detection.

playbooks/roles/l2tp-ipsec/vars/main.yml
The unreliable official download location strikes again!
=> Download the Libreswan sig file from the same endpoint as the source.

playbooks/roles/common/tasks/main.yml, playbooks/roles/common/vars/main.yml
These services are part of default Ubuntu installation. Since Streisand
doesn't use any of those, it's safe to remove them completely.
Closes #703
=> Remove lxd and snapd from default installation

playbooks/roles/streisand-mirror/vars/openvpn.yml
It would appear that the OpenVPN team has a new GPG key used to sign releases for v2.4.3+.
This PR addresses mirroring errors failures due to the new key.
Resolves #752
=> Update the OpenVPN mirror GPG key and fingerprint

tests/development-setup.yml
The Ansible `apt_repository` module at the time of writing is choking on
the ubuntu-lxc ppa repository because one of the mirrors is missing
binary-i386 builds. We don't actually **use** i386 builds because Travis
is x86_64 by default. We can work around this error by using the
`add-apt-repository` via the Ansible `command` module instead of doing
things the "right" way. This can be reverted when the upstream
`add-apt-repository` module is fixed.
Resolves https://github.com/jlund/streisand/issues/758
=> Fix CI by working around Ansible `apt_repository` bug.

.travis.yml, documentation/testing.md, streisand, tests/development-setup.yml, tests/tests.sh, util/ansible_check.sh
Per Travis docs the way to have the build exit if one script fails is
to only specify one script and rely on shell operators to short circuit
on non-zero exit. Kind of ugly... but ok Travis............ if you say
so..........................
Resolves https://github.com/jlund/streisand/issues/725
This PR updates `tests/tests.sh` to have less duplication & to pass
a shellcheck invocation. The commonality between it and the base
`streisand` script was extracted to `util/ansible_check.sh` and included
in both places. To make shellcheck follow the includes we add a `-x` to
the `.travis.yml` invocation of shellcheck. A handful of if statements were
replaced by a case statement. Common ansible-playbook invocation
was refactored to a function.
This PR adds some high level documentation about CI …
=> CI enhancements/shell script cleanup

playbooks/group_vars/all, playbooks/roles/common/vars/main.yml, playbooks/roles/download-and-verify/tasks/main.yml, playbooks/roles/streisand-mirror/tasks/tor-common.yml, playbooks/roles/streisand-mirror/tasks/tor-download.yml, playbooks/roles/streisand-mirror/tasks/tor-verify.yml, playbooks/roles/streisand-mirror/tasks/tor.yml, playbooks/roles/streisand-mirror/templates/mirror-index-fr.md.j2, playbooks/roles/streisand-mirror/templates/mirror-index.md.j2, playbooks/roles/streisand-mirror/vars/tor-common.yml, playbooks/roles/streisand-mirror/vars/tor-download.yml, playbooks/roles/streisand-mirror/vars/tor-mirror.yml, tests/group_vars/all/all
In order to support mirroring localized versions of Tor, steps taken from the `download-and-verify` task were unrolled and modified into three distinct steps specifically for Tor:
1. `tor-common`&nbsp;&nbsp;&nbsp;&nbsp;- Determining the recommended TBB version and registering the GPG keys
2. `tor-download`&nbsp;- Downloads TBB for the locales defined in `streisand_languages`
3. `tor-verify`&nbsp;&nbsp;&nbsp;&nbsp;- Integrity verification 
Furthermore, the download task is gated only to available locales that TBB supports defined as `tor-available-locales`.
=> Adds support for mirroring localized versions of the Tor Browser Bundle

playbooks/roles/shadowsocks/vars/main.yml
This PR updates `shadwosocks-libev` tag from `3.0.6` -> `3.0.7`. 
In addition to this, stale variables which are not used any more with the `git clone` subtask are removed.
This PR fixes #765
=> Update SS-libev version and remove stale variables

playbooks/roles/common/tasks/main.yml
Previous to this commit the `playbooks/roles/common/tasks/main.yml`
block for enforcing that the machine is Ubuntu 16.04 was only checking
the `ansible_distribution` and the `ansible_distribution_major_version`,
meaning that Ubuntu 16.10 was treated the same as Ubuntu 16.04.
This commit reworks the check to enforce that
`ansible_distribution_version` is exactly 16.04.
Resolves https://github.com/jlund/streisand/issues/398 
Thanks to @damongant for the report
=> Enforce ansible_distribution_version is exactly 16.04

playbooks/roles/common/files/50unattended-upgrades
This PR updates the `50unattended-upgrades` configuration file that Streisand places in `/etc/apt/apt.conf.d` to add additional options for how to handle dpkg conffile conflicts.
If a package (e.g. `tor`) has a security update and a change to a config file (e.g. `/etc/tor/torrc`), and Streisand has modified that config file, then the security update will stall at a dpkg conffile prompt asking if the user wants to keep the modified Streisand config file or the new package one. This obviously isn't very good for headless servers. Instead, we want unattended-upgrades to leave the Streisand configuration in place 100% of the time and have the new config file placed next to it with a `.dpkg-dist` suffix.
To do so the `--force-confdef` and `--force-confold` dpkg options are used. More about …
=> Update unattended-upgrades config to avoid conffile prompts.

playbooks/roles/shadowsocks/tasks/simple-obfs.yml, playbooks/roles/shadowsocks/vars/main.yml
With Shadowsocks simple-obfs v0.0.3 multiple invocations of the Shadowsocks playbook will error with the following:
"changed": false, "failed": true, "msg": "Local modifications exist in repository (force=no)."
Looking in the `simple_obfs_compilation_directory` we see that `aclocal.m4` has local modifications:
```
/usr/local/src/shadowsocks-libev-0.0.3# git status
HEAD detached at v0.0.3
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git checkout -- <file>..." to discard changes in working directory)
modified:   aclocal.m4
```
While `aclocal.m4` [is present in the simple-obfs `.gitignore`](https://github.com/shadowsocks/simple-obfs/blob/ace8bd27a7a68fceb884937d938619dd7dfe5420/.gitignore#L3), it was checked into the repository beforehand …
=> Fix simple-obfs git clone local modifications conflict.

playbooks/roles/tor-bridge/tasks/main.yml, playbooks/roles/tor-bridge/vars/main.yml
This PR adds a `wait_for` task for the `/var/lib/tor/fingerprint` file that we depend on existing later in the tor-bridge role. 
Additionally this PR moves some of the hardcoded task paths into vars and adds some quoting for safety.
Resolves #780.
=> Wait for the tor fingerprint file, move paths to vars.

playbooks/roles/shadowsocks/tasks/main.yml
The order of https://github.com/jlund/streisand/pull/794 and https://github.com/jlund/streisand/pull/795 getting merged snuck a yamllint error into master that now breaks the build.
This PR fixes the error and the travis build. Sorry about that!
=> Remove extra blank line to fix yamllint err.

README-fr.md, README.md
In the effort to make Streisand available when Github is not there is
a Gitlab mirror of Streisand available at
https://area51.threeletter.agency/mirrors/streisand
@cpu maintains this mirror.
Resolves https://github.com/jlund/streisand/issues/421
=> Add Streisand mirror to README.

playbooks/roles/ec2-security-group/tasks/main.yml
As part of the modularization work the ec2-security-group task that
adds rules for each of the service ports was broken into three tasks:
1. a task for all of the unmodular ports.
2. a task that opened Shadowsocks ports when
`streisand_shadowsocks_enabled` was true
3. a task that opened Wireguard ports when
`streisand_wireguard_enabled` was true.
This design assumed that multiple `ec2_group` invocations was additive,
that is, that the three tasks would add to the same security group.
Instead the last `ec2_group` task is the only one that is used, in
effect only opening the Wireguard port for a default install.
I suspect there is a way to properly open only the required ports based
on the `enabled` vars but in the interest of fixing a regression on
master quickly this PR restores the …
=> Restore the unconditional ec2-security-group tasks.

playbooks/roles/streisand-mirror/vars/openvpn.yml
Due to some [CDN related issues](http://community.openvpn.net/openvpn/wiki/release-packages-2.4.3-2.3.17), OpenVPN's latest releases are now being signed with GPG key ID `0x29584D9F40864578`.
This PR updates the OpenVPN mirroring task to reflect this change (once more).
Resolves #811
=> OpenVPN mirror fix

playbooks/roles/genesis-google/tasks/main.yml
Prior to this commit the GCE genesis role was setting the `ansible_user`
to `ubuntu`. This appears to be a mistake since in the earlier `gce`
task it adds the SSH key under the `root` user.
In testing a GCE provision recently I noticed that the cloud-init task
would fail with an SSH "Permission denied (publickey)" error. Similar
`raw` tasks would fail if the cloud-init include was commented out.
In practice using `root` as the `ansible_user` for GCE allows
provisioning to complete without error.
It's not clear to me why this didn't break before since the
`ansible_user` has been static for some time... Mysterious!
=> Set GCE `ansible_user` to `root` to match SSH key metadata.

playbooks/roles/ec2-security-group/tasks/main.yml
This PR re-enables the functionality that was rolled back in #814. We can prevent the issues that were reported in #810 using the `purge_rules` and `purge_rules_egress` arguments. When these arguments are set to `no`, repeated invocations of the `ec2_group` module don't blow away existing inbound and outbound rules.
=> Enable conditional rules for modular roles in EC2 Security Groups

playbooks/roles/wireguard/templates/instructions-fr.md.j2, playbooks/roles/wireguard/templates/instructions.md.j2, playbooks/roles/wireguard/templates/wg0-client.conf.j2
This came out with 0.0.20170726, and merging it probably should depend on @EggieCode pushing the package to the Ubuntu PPA.
=> wireguard: use the new DNS setting

README-fr.md, README.md, playbooks/roles/wireguard/templates/instructions-fr.md.j2, playbooks/roles/wireguard/templates/instructions.md.j2
The WireGuard project is moving from wireguard.io to wireguard.com:
https://lists.zx2c4.com/pipermail/wireguard/2017-July/001569.html
=> Update documentation to reflect the new WireGuard domain

playbooks/roles/l2tp-ipsec/tasks/main.yml, playbooks/roles/l2tp-ipsec/templates/instructions.md.j2, playbooks/roles/l2tp-ipsec/templates/streisand.mobileconfig.j2
Disclaimer: I am not an ansible person; would love someone to clean up.
The `.mobileconfig` generated is very similar to what OS X Server emits. Note that we can't configure "AlwaysOn" VPNs because that apparently requires a "managed" device, and nobody really wants that.
See https://developer.apple.com/library/content/featuredarticles/iPhoneConfigurationProfileRef/Introduction/Introduction.html for more information on these config files.
This PR addresses half of #136 (we still need to generate some mobileconfig containing our server certs) and I am ignoring the similar #512 until I understand what that “connect on demand” checkbox really does. (Probably not what you’d think.)
=> Add an iOS/OS X .mobileconfig file for L2TP

global_vars/vars.yml, playbooks/roles/monit/templates/monitrc.j2, playbooks/roles/ssh/templates/instructions-fr.md.j2, playbooks/roles/ssh/templates/instructions.md.j2, playbooks/streisand.yml
This PR modifies Streisand to make the tinyproxy role optional, which can be configured by modifying the `streisand_tinyproxy_enabled` to `no`, located in `global_vars/vars.yml`.
Updates #746.
=> Optional tinyproxy

playbooks/roles/nginx/tasks/main.yml, playbooks/roles/streisand-gateway/handlers/main.yml, playbooks/roles/streisand-gateway/tasks/main.yml, playbooks/roles/tor-bridge/handlers/main.yml, playbooks/roles/tor-bridge/tasks/main.yml
Previously, the Nginx restart handler was located in the Nginx role. The `tor-bridge` and `streisand-gateway` roles declared a dependency on the Nginx role and notified the same handler for their respective vhost template tasks.
The issue with this approach in a modular world is that the Tor role runs prior to the Gateway role. The Nginx role (and its handler) are skipped as declared dependencies of the Tor role if the `streisand_tor_enabled` variable is set to 'no'. Later on, the Nginx tasks run successfully when the Gateway role also declares a dependency on Nginx. However, Ansible still treats the handler as having been skipped and won't execute the restart task because handlers only run once and the first skip takes precedence.
This PR moves the handlers into each role with unique …
=> Refactor the Nginx restart tasks to support modularity

playbooks/roles/monit/templates/monitrc.j2
When the handler to restart Nginx was skipped due to #873, Monit would start the Nginx daemon using the legacy `/etc/init.d/nginx start` command. This broke future invocations of the `service nginx restart` and `service nginx stop` commands. The same was true for other daemons that Monit launched (or re-launched).
@alimakki first documented the symptoms of this problem in #871.  Although default installations were insulated from this bug, and #873 should prevent it from occurring again in the future, Monit can still be a good init citizen until we replace it with something better.
=> Update the Monit config to use the `service` init wrapper

streisand
On Arch Linux `/usr/bin/python` is Python 3. When executing the playbook
on an Arch Linux laptop, there are actually some modules executed
locally, e.g. `ec2_*` ones. Without proper `ansible_python_interpreter` set
these tasks would fail.
=> Always do check_python()

playbooks/roles/shadowsocks/tasks/main.yml
When configuring with `--prefix=/usr`, the binaries are installed under
the directory `/usr/bin` instead of `/usr/local/bin`.
=> shadowsocks: Make installation idempotent

playbooks/roles/streisand-gateway/templates/firewall-fr.md.j2, playbooks/roles/streisand-gateway/templates/firewall.md.j2
Variable `stunnel_remote_port` is only available when we have run the stunnel role. There are two references of `stunnel_remote_port` in the docs, but only one of them is surrounded by `{% if
streisand_stunnel_enabled %}{% endif %}`. This causes "AnsibleUndefinedVariable" error when we disabled stunnel role and run gateway role.
This commit fixes the bug by surrounding the other reference with `{% if %}{% endif %}`, as well.
=> docs: Fix undefined variable

playbooks/roles/openconnect/templates/instructions-fr.md.j2
Updates the OpenConnect/AnyConnect instructions for prompted username/password bug on Android #894
=> Update French Openconnect/Anyconnect instructions

playbooks/roles/ssh-forward/meta/main.yml, playbooks/streisand.yml
Variable `ssh_port` is used by so many other roles, it's only set in ssh
role. But ssh role is only depended by ssh-forward role. Setting
`streisand_ssh_forward_enabled` to false destroies every reference to
`ssh_port`.
=> Always run ssh role

playbooks/roles/genesis-google/tasks/main.yml
This reverts commit e04b034f0b256a791b197d267becee6b90d16e10.
It appears the GCE image is back to requiring use of the `ubuntu` user vs `root`:
> "module_stdout": "Please login as the user \"ubuntu\" rather than the user \"root\".\n\n"
=> Revert "Remove GCE `ansible_user`/`become_user` (#829)"

playbooks/cloud-status.yml, playbooks/google.yml, playbooks/provider-detect.yml, playbooks/roles/download-and-verify/tasks/main.yml, playbooks/roles/genesis-amazon/tasks/main.yml, playbooks/roles/genesis-azure/tasks/main.yml, playbooks/roles/genesis-digitalocean/tasks/main.yml, playbooks/roles/genesis-google/tasks/main.yml, playbooks/roles/genesis-linode/tasks/main.yml, playbooks/roles/l2tp-ipsec/tasks/main.yml, playbooks/roles/openconnect/tasks/main.yml, playbooks/roles/openvpn/tasks/main.yml, playbooks/roles/shadowsocks/tasks/main.yml, playbooks/roles/ssh-forward/tasks/main.yml, playbooks/roles/streisand-gateway/tasks/main.yml, playbooks/roles/stunnel/tasks/mirror.yml, playbooks/roles/tor-bridge/tasks/main.yml, playbooks/roles/wireguard/tasks/main.yml, tests/run.yml
Some tasks are just used to register file contents. These read-only tasks should not return "changed" in Ansible. Adding `changed_when: False` ensures a task no more returns "changed", only "ok" or "failed".
Hope I did not miss some tasks...
=> Do not show "changed" when running read-only tasks

playbooks/roles/genesis-amazon/tasks/main.yml
There's a 90-second pause in EC2 provisioning where we wait for SSH to
start working. The bug this worked around was not reproducible recently. Delete the pause.
----
Original message:
My guess was that /dev/random is starved for entropy. Use haveged at cloud-init to start gathering some entropy.
Do we trust/like haveged?
I’m leaving the 90-second pause commented out (instead of deleted), in case somebody suddenly runs into this bug again. I’m open to opinion on that.
=> Eliminate the EC2 90-second pause for ssh

playbooks/roles/openconnect/tasks/main.yml, playbooks/roles/openconnect/templates/client.tmpl.j2, playbooks/roles/openconnect/templates/config.j2, playbooks/roles/openconnect/vars/main.yml
- openconnect client certificates uses the generated VPN client names as CN rather than an IP address, allowing ocserv to distinguish between users
- set the max-same-clients to 1
Tested on a DO droplet with multiple simultaneous users, no issues.
Edit: typo
=> Correctly limit OpenConnect clients

global_vars/vars.yml, playbooks/roles/validation/tasks/main.yml, playbooks/streisand.yml, playbooks/vagrant.yml, playbooks/validate.yml, streisand, tests/development-setup.yml, tests/yamllint-config.yml
- added validation task to execute from Streisand script prior to installer running
- modified vagrant test run to include validation role
- modified CI task to include validation role
- ensure that at least one VPN is selected, otherwise we have a gateway that feels empty inside
- sorted modular variables in ascending order
- bumped yaml lint max characters to 280, reduces CI noise
Resolves #913
=> Validation refactor

README-chs.md, README-fr.md, README.md, documentation/SOURCES.md, playbooks/roles/ssh-forward/tasks/main.yml, playbooks/roles/ssh-forward/tasks/mirror.yml, playbooks/roles/ssh-forward/templates/instructions-fr.md.j2, playbooks/roles/ssh-forward/templates/instructions.md.j2, playbooks/roles/ssh-forward/templates/mirror-fr.md.j2, playbooks/roles/ssh-forward/templates/mirror.md.j2, playbooks/roles/ssh-forward/vars/main.yml, playbooks/roles/ssh-forward/vars/mirror.yml
By default one can log into the Streisand server with the SSH private
key, which is intended for port forwarding. This poses a security issue
if a careless sysadmin sets open permissions on critical files.
Prepending a force command to authorized_key is a simple way to
prevent SSH login with that key.
=> ssh-forward: Allow port forwarding only

playbooks/roles/shadowsocks/vars/mirror.yml
https://github.com/shadowsocks/shadowsocks-android/releases/tag/v4.2.5
=> Update shadowsocks android client mirror to v4.2.5.

.github/ISSUE_TEMPLATE.md, .gitignore, playbooks/existing-server.yml, playbooks/localhost.yml, playbooks/roles/diagnostics/tasks/main.yml, playbooks/roles/diagnostics/templates/streisand-diagnostics.md.j2, playbooks/roles/genesis-amazon/tasks/main.yml, playbooks/roles/genesis-azure/tasks/main.yml, playbooks/roles/genesis-digitalocean/tasks/main.yml, playbooks/roles/genesis-google/tasks/main.yml, playbooks/roles/genesis-linode/tasks/main.yml, playbooks/roles/genesis-rackspace/tasks/main.yml, playbooks/streisand.yml
This commit adds a diagnostics role that is used to collect information
about the Ansible installation & the Streisand clone being run. This
information is written to `streisand-diagnostics.md` in the project
directory but **not shared anywhere**. Care was taken to not include
anything that is especially sensitive (e.g. IP addresses, BIOS info).
The information written to the `streisand-diagnostics.md` file includes:
* Ansible version
* Host OS/version
* Python version
* Streisand git revision
* Whether there are untracked changes in the git clone (e.g. you've
mucked about!)
* The genesis role that was being used (Linode, EC2, Localhost, etc)
* Which optional roles were enabled
* How many VPN clients were being configured
This commit updates the Github issue template to indicate that …
=> Collect diagnostic info locally & suggest sharing in new issues

playbooks/roles/diagnostics/templates/streisand-diagnostics.md.j2
Seems that some versions of Ansible we support don't have this var
defined (https://github.com/jlund/streisand/issues/931). It would be easy enough to work around this with a default
value but I was on the fence about the value of including it to begin
with so for now out it goes!
=> Remove `ansible_architecture` from diagnostics.

playbooks/roles/shadowsocks/vars/mirror.yml
https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.0.6
Notably this release adds support for SIP003 which might mean that
simple-obfs will work with Windows clients soon. Neat-o.
=> Update Shadowsocks Windows client mirror to 4.0.6

playbooks/roles/diagnostics/templates/streisand-diagnostics.md.j2
This commit updates the `streisand-diagnostics md.j2` template to
conditionally reference hostvars for diagnostics. If the hostvars don't
exist the diagnostic is templated as Unknown.
For mysterious reasons it seems like sometimes the same version of
Ansible will have different hostvars populated. Since we intend for this
diagnostics information to be useful in cases when things are already
going wrong we should take the most conservative approach possible in
collecting the information.
One might be tempted to use `.get('foo', 'Unknown')` or similar instead
of a mess of `if/else/endif` blocks. Unfortunately the Ansible
`hostvars` var isn't a normal dict and this will still fail if `'foo'`
isn't defined.
Updates #931
=> Conditionally access hostvar keys for diagnostics.

playbooks/roles/l2tp-ipsec/templates/instructions.md.j2, playbooks/roles/streisand-gateway/templates/instructions.md.j2
My experience was that auto-install did not happen when using Chrome for iOS or Google Inbox, only when using the Apple apps.
=> Specify using iOS apps.

README.md
Without `packaging`, the following error emits:
```
TASK [azure-security-group : Create Azure resource group] **********************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named packaging.version
```
Fixes #735
=> Fix Azure Python dependency

playbooks/roles/validation/tasks/main.yml
The validation role didn't include `streisand_shadowsocks_enabled` in
the boolean logic used to decide if no VPN services were enabled. As
a result configuring Streisand with only shadowsocks enabled fails. This
commit adds `streisand_shadowsocks_enabled` to the validation check and
now you can provision a Streisand node that has only shadowsocks-libev.
=> Fix missing `streisand_shadowsocks_enabled` check in validation role.

playbooks/roles/shadowsocks/tasks/simple-obfs.yml, playbooks/roles/shadowsocks/vars/main.yml
This commit updates the git source of `shadowsocks-libev` that Streisand
clones to version 3.1.0. This release removes udns support so we can
drop `libundns-dev` from `shadowsocks_dependencies`. Shadowsocks-libev
now uses `libc-ares-dev` so we add that dep in its place.
Unfortunately the latest tagged release of simple-obfs is 0.0.3 and
still uses `libudns-dev`. This commit switches to cloning the tip of
master while waiting for a release.
I tested a Shadowsocks Android client against a fresh server both with
and without simple-obfs and both worked correctly using a 3.1.0 server.
=> Update shadowsocks-libev to 3.1.0, simple-obfs to tip of master.

playbooks/provider-detect.yml
We use `dmidecode` to query BIOS information. It fails on a rpi2/rpi3,
and will on other platforms too. Set the BIOS name to "Unknown"
rather than bombing out the playbook.
=> Provisioning: don't fail on dmidecode failure

playbooks/roles/diagnostics/templates/streisand-diagnostics.md.j2
This fixes an error that was otherwise occurring when running one of the advanced installation options against an existing server.
Resolves https://github.com/jlund/streisand/issues/956
=> Set a default value for the Genesis Role diagnostic variable.

playbooks/roles/common/vars/main.yml, playbooks/roles/l2tp-ipsec/vars/main.yml, playbooks/roles/openconnect/vars/main.yml, playbooks/roles/openvpn/vars/main.yml, playbooks/roles/wireguard/vars/main.yml
Per `man iptables`:
```
-w, --wait [seconds]
Wait  for  the xtables lock.  To prevent multiple instances of the
program from running concurrently, an attempt will be made to
obtain an exclusive lock at launch.  By default, the program will
exit if the  lock  cannot  be  obtained. This  option  will  make
the  program  wait  (indefinitely  or for optional seconds) until
the exclusive lock can be obtained.
```
Since Streisand presently uses `iptables` in multiple services at boot
without explicit coordination it makes sense to wait a little longer when
invoking `iptables`. We will suffer the boot time slowdown that may
occur until we can perform a larger firewall cleanup (See Issue #950).
By default we now wait 120 seconds as specified in the `common`
playbook's `streisand_iptables_wait` …
=> Always use `iptables` with `--wait` in firewall rules.

README-chs.md, README-fr.md, README-ru.md, README.md
Quick PR to fix the Travis CI badges after the repository move. I will follow up this PR with another that updates all instances of the old Github URL across the project.
=> Update Travis badge README links.

.travis.yml, playbooks/amazon.yml, playbooks/azure.yml, playbooks/digitalocean.yml, playbooks/existing-server.yml, playbooks/google.yml, playbooks/linode.yml, playbooks/localhost.yml, playbooks/rackspace.yml, playbooks/roles/common/tasks/main.yml, playbooks/roles/l2tp-ipsec/tasks/main.yml, playbooks/roles/lets-encrypt/tasks/main.yml, playbooks/roles/openconnect/tasks/main.yml, playbooks/roles/openvpn/tasks/main.yml, playbooks/roles/shadowsocks/tasks/main.yml, playbooks/roles/ssh-forward/tasks/main.yml, playbooks/roles/streisand-gateway/tasks/main.yml, playbooks/roles/stunnel/tasks/main.yml, playbooks/roles/test-client/tasks/main.yml, playbooks/roles/test-client/tasks/wireguard.yml, playbooks/roles/tor-bridge/tasks/main.yml, playbooks/roles/tor-bridge/tasks/mirror.yml, playbooks/roles/wireguard/tasks/main.yml, playbooks/streisand.yml, playbooks/vagrant.yml, tests/ansible.cfg, tests/run.yml, tests/syntax-check.yml, util/ansible_check.sh
This patch updates `include` syntax to `import_tasks` `include_tasks` `import_playbook`, and raises the required version of Ansible to 2.4.
I have tested this on a fresh EC2 instance, all went well.
Ref: https://github.com/StreisandEffect/streisand/issues/994
=> Update to Ansible 2.4 syntax

global_vars/default-site.yml
Previous to this commit the `default-site.yml` file that was used to
initialize the user's `~/.streisand/site.yml` used `~/.ssh/id-rsa` as
the default SSH private key file location if one were not specified.
`ssh-keygen` actually uses `~/.ssh/id_rsa` (note the underscore) and so
we should too. This commit updates the default
`streisand_ssh_private_key` value from `default-site.yml` accordingly.
Resolves https://github.com/StreisandEffect/streisand/issues/1001
=> Fix the default-site ssh_private_key filepath.

playbooks/roles/streisand-gateway/templates/index-fr.md.j2, playbooks/roles/streisand-gateway/templates/index.md.j2, playbooks/roles/streisand-mirror/tasks/main.yml
If no roles are enabled that mirror client software then the index page
shouldn't reference a mirrored software page and we should not generate
one.
Resolves https://github.com/StreisandEffect/streisand/issues/961
=> Only generate Mirror page when there is mirrored software.

documentation/certificates.md, playbooks/roles/certificates/defaults/main.yml, playbooks/roles/certificates/tasks/ca-server.yml, playbooks/roles/certificates/tasks/client.yml, playbooks/roles/certificates/tasks/main.yml, playbooks/roles/certificates/templates/openssl.cnf.j2, playbooks/roles/certificates/vars/main.yml, playbooks/roles/openconnect/tasks/main.yml, playbooks/roles/openconnect/templates/ca.tmpl.j2, playbooks/roles/openconnect/templates/client.tmpl.j2, playbooks/roles/openconnect/templates/instructions-fr.md.j2, playbooks/roles/openconnect/templates/instructions.md.j2, playbooks/roles/openconnect/templates/server.tmpl.j2, playbooks/roles/openconnect/vars/main.yml, playbooks/roles/openvpn/tasks/main.yml
This PR aims to refactor CA/Server/Client certificate generation into its own role (in a similar vein as the download-and-veryify role) with the goals of:
- Reducing code duplication by way of centralizing certificate generation
- Separation of CA/server and client certificate generation into separate tasks (separation of concerns)
- Simplify any future endeavor if OpenSSL need be replaced with alternative cryptography toolkits (e.x. LibreSSL)
Additionally, the changes in this PR will now assign subject alternative names to (the self-signed) server certificate, which may help in addressing the issue presented in #906 (to be issued in a separate PR).
The OpenVPN and OpenConnect roles have been refactored to utilize the role, without any observable regressions thus far.
=> Refactor OpenSSL CA/Server/Client certificate generation into its own role

documentation/certificates.md, playbooks/roles/certificates/defaults/main.yml, playbooks/roles/certificates/tasks/client.yml, playbooks/roles/certificates/tasks/main.yml, playbooks/roles/certificates/tasks/pkcs.yml, playbooks/roles/openconnect/tasks/docs.yml, playbooks/roles/openconnect/tasks/main.yml, playbooks/roles/openconnect/templates/instructions-fr.md.j2, playbooks/roles/openconnect/templates/instructions.md.j2, playbooks/roles/openvpn/tasks/main.yml
This PR refactors the certificates role to do the following tasks: 
- the underlying `client.yml` task is now responsible for generating client directories, reducing code duplication across the openvpn and ocserv roles
- adds an additional task to generate client pkcs files, guarded by the `generate_pkcs` flag.
- update and clean up the certificates documentation.
=> Refactor certificates role

README.md, deploy/streisand-existing-cloud-server.sh, deploy/streisand-local.sh, deploy/streisand-new-cloud-server.sh, global_vars/noninteractive/amazon-site.yml, global_vars/noninteractive/azure-site.yml, global_vars/noninteractive/digitalocean-site.yml, global_vars/noninteractive/google-site.yml, global_vars/noninteractive/linode-site.yml, global_vars/noninteractive/local-site.yml, global_vars/noninteractive/rackspace-site.yml, playbooks/provider-detect.yml, playbooks/roles/common/tasks/main.yml, playbooks/roles/download-and-verify/tasks/main.yml, playbooks/roles/tor-bridge/tasks/mirror-verify.yml, streisand, util/ansible_check.sh, util/source_check_and_default_site_vars.sh, util/source_validate_and_deploy.sh
This PR is a proposed simple noninteractive deployment.
- Make a few changes to Ansible where needed to allow some prompts to be bypassed.
- Provide example vars files.
- Create some additional bash scripts to run non-interactive deployments.
- Remove duplicate function definitions from the `streisand` script.
- Add English documentation on running the new scripts.
It is possible, somewhat, to shoehorn all of the new bash scripting into the main `streisand` script, but it gets pretty ugly with if-blocks and checks if you do that. I'm not in favor of kitchen sink scripts - the code is much simpler and more maintainable when split out in this way.
Example configuration files are found under `global_vars/noninteractive`. Copy and edit the desired parameters, such as providing API tokens and …
=> Set up a simple noninteractive deployment mode.

streisand
This commit updates the Streisand script's `customize` function to
clarify that if you do not enter "yes" the site vars file will be used.
Resolves https://github.com/StreisandEffect/streisand/issues/1039
=> Clarify that not customizing will use site vars file.

playbooks/roles/shadowsocks/tasks/simple-obfs.yml, playbooks/roles/shadowsocks/vars/main.yml
The upstream shadowsocks simple-obfs project has cut a 0.0.4 release
that contains the bugfixes/work that we were relying on. This lets us
delete the hardcoded commit we were referencing as well as a workaround
for a bug in tree leaving the work dir dirty.
=> Replace hardcoded simple-obfs commit with tag v0.0.4

playbooks/roles/certificates/tasks/pkcs.yml
Cleans up the certificates role by replacing the use of certtool to create ~~certificates~~ PKCS#12 files, opting instead for OpenSSL as used throughout the rest of the role.
This also brings us the additional benefit of passing the PKCS#12 passwords as an argument rather than relying on expect.
Tested on a Linode instance with no issues. 
Edit: clarification
=> User OpenSSL for PKCS12 generation

playbooks/roles/genesis-google/tasks/main.yml
Per the GCE docs on SSH [metadata](https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys):
> Note: Setting the sshKeys metadata value on project metadata is
> deprecated. Use the ssh-keys metadata value instead. If instances in
> your project uses older images, you might need to update the guest
> environments for these instances.
This commit updates the metadata key to be "ssh-keys" instead of
"sshKeys", fixing the problem where GCE provisioning required manual
intervention to fix SSH access.
Thanks to @vadimzharov for spotting the problem and providing the fix!!
I deleted all of the SSH keys and metadata on my GCE account and was
able to use this branch to provision a new instance without error where 
previously I had to attach an SSH key in the console manually. …
=> Use correct SSH keys metadata for GCE provisioning.

playbooks/roles/lets-encrypt/tasks/main.yml, playbooks/roles/lets-encrypt/vars/main.yml
As @cpu [pointed out](https://github.com/StreisandEffect/streisand/pull/1054#issue-275086994), there is an ACME API for querying the latest TOS. So we can actually fetch the TOS URL when running the playbook, instead of hardcoding it.
=> lets-encrypt: Query Let's Encrypt for current agreement URL

tests/tests.sh
In `tests/tests.sh`, the variable SITE may not be set in `run_playbook`. If it's not set, don't add a bare `--extra-vars=` to Ansible invocation.
Resolves https://github.com/StreisandEffect/streisand/issues/1052
=> tests.sh: If $SITE is empty, don't include its --extra-vars clause.

playbooks/roles/shadowsocks/vars/main.yml
The upstream `shadowsocks-libev` project has [cut a 3.1.1 release](https://github.com/shadowsocks/shadowsocks-libev/releases/tag/v3.1.1). It
addresses a security vulnerability with `ss-manager`, and while
Streisand doesn't use this utility we should keep up-to-date regardless.
=> Update shadowsocks-libev version to 3.1.1

playbooks/roles/shadowsocks/vars/main.yml
The [upstream](https://github.com/shadowsocks/simple-obfs) project has released an updated version of `Simple-Obfs` plugin. [Changelog](https://github.com/shadowsocks/simple-obfs/blob/master/Changes) mentions a fix for building on windows.
=> Update Simple-Obfs version to 0.0.5

playbooks/roles/wireguard/tasks/docs.yml, playbooks/roles/wireguard/tasks/main.yml, playbooks/roles/wireguard/templates/client.conf.j2, playbooks/roles/wireguard/templates/instructions-fr.md.j2, playbooks/roles/wireguard/templates/instructions.md.j2, playbooks/roles/wireguard/templates/server.conf.j2, playbooks/roles/wireguard/templates/wg0-server.conf.j2, playbooks/roles/wireguard/vars/main.yml
This commit updates the WireGuard playbook to follow the client
generation approach used by the OpenVPN playbook. This means using the
BIP-0039 randomly generated client names & honouring the `vpn_clients`
var to determine how many client profiles to make. Like OpenVPN only one
client profile may be in use at a time.
I added un peu de mauvais français to keep the translations ~= in-sync.
Forgive my Franglais.
Thanks to @alimakki for helping me figure out some of the templating :-)
Resolves https://github.com/StreisandEffect/streisand/issues/693
=> Generate multiple WireGuard client profiles.

tests/ansible.cfg
`tests/tests.sh syntax` blows up because it can't import modules from the primary playbook directory.
=> tests.sh: use the main Ansible playbook as well

playbooks/roles/streisand-gateway/templates/vhost.j2
Like it or not, a lot of people depend on being able to click through the "this cert sucks" page on non-LE servers. HSTS prohibits click-throughs. Perhaps "lots of people depend" is a little strong, but there are going to be people who get stuck on this step.
=> Don't turn on HTTP Strict Transport Security on non-LE servers

playbooks/roles/openvpn/templates/instructions-fr.md.j2, playbooks/roles/openvpn/templates/instructions.md.j2
Previous to this commit the "Linux (Ubuntu)" NetworkManager instructions
for configuring OpenVPN with a client profile instructed users to
download several files from a raw directory index. This broke in 811bea1
when we added `autoindex off;` to the nginx config.
This commit updates the OpenVPN instructions template (for EN and FR) to
directly link to each of the required files instead of relying on the
directory index. This is a better user experience overall, directory
indexes are ugly!
My FR updates are probably très mauvais. Je suis désolé!! :-x
Thanks to @Spengreb  for flagging the issue initially in https://github.com/StreisandEffect/streisand/pull/1075
=> Direct link to NetworkManager OpenVPN files.

requirements.txt, util/venv-dependencies.sh
Currently we keep track of which Python packages are needed in several different places. I generally consider the README to be definitive. But the README isn't machine-readable.
This adds a `requirements.txt` listing all Python dependencies. I've been stalling on README updates, but it'd be cool if the easy instruction were "install pip, then `pip install -r requirements.txt`. There's always virtualenvs if people run into dependency problems--but venv-builder needs to be put in the README too.
I can do the README mods either in this PR or another one.
=> Centralize Python requirements in a requirements.txt

util/ubuntu-dependencies.sh
I spun up an instance using `ubuntu-dependencies.sh` as a cloud-init script. Warn people they need to turn on some options if they're doing that.
=> Clarify what must be done to use ubuntu-deps as a cloud-init

playbooks/roles/openvpn/templates/instructions-fr.md.j2, playbooks/roles/openvpn/templates/instructions.md.j2
We do not generate any profiles that would mimick HTTP on port 80, only
HTTPS on 443.
Resolves #1074
=> Clarify that SSLH OpenVPN profiles are for port 443.

playbooks/roles/certificates/tasks/ca-server.yml, playbooks/roles/certificates/tasks/pkcs.yml, playbooks/roles/common/tasks/main.yml, playbooks/roles/common/vars/main.yml, playbooks/roles/l2tp-ipsec/tasks/main.yml, playbooks/roles/openconnect/tasks/main.yml, playbooks/roles/streisand-gateway/tasks/main.yml, playbooks/roles/tor-bridge/tasks/main.yml
This reverts commit 3d153287c889cc95f268e82d5807ea82b573f6a9, reversing changes made to 9baef3eceeaf94cd823eb376eee00096de2f7b15.
This commit was causing a [tor regression](https://github.com/StreisandEffect/streisand/issues/1103). 
Resolves #1103 
_Note: Happy to close this if we have a fix for the root cause of 1103 to prefer_
=> Revert "Switch to BIP identifiers/password generation"

playbooks/roles/common/vars/main.yml, playbooks/roles/tor-bridge/tasks/main.yml
For nicknames, we need 1-19 characters from `[A-Za-z0-9]`. Our wordlist has a bunch of 8-character words, so we're limited to two words for this. **TitleCase** the words for moderately better recognition. Chop at 18 characters in case our wordlist gets expanded.
=> Fix tor bridge nickname

util/ubuntu-dependencies.sh, util/venv-dependencies.sh
As `pycurl` is required for `linode-python`, `pycurl` also depends on having `libssl-dev` and `libcurl4-openssl-dev` to be installed prior to setup.
This PR updates the `ubuntu-dependencies.sh` and `venv-dependencies.sh` scripts to require the dependencies, ensuring a smooth and clean setup process.
As the pip requirements are now externalized into a separate file, an additional minor refactor makes use of the text file in `ubuntu-dependencies.sh`, reducing duplicate code.
Tested on 2 fresh Digital Ocean droplets, one running the first script only and the other running the latter with no apparent issues.
=> Update ubuntu-dependences and venv-scripts

playbooks/roles/tinyproxy/tasks/main.yml
Prior to this commit the TinyProxy config on the Streisand server only
had an entry for `Allow 127.0.0.1` - You would _think_ this would be
sufficient for a port forwarded request to be allowed but testing seems
to indicate (You need to increase the verbosity level to see this) the
connection is refused as coming from the Streisand server's own IP. The
client is given a 403 Access Denied error page in response from
TinyProxy.
TinyProxy only binds to `127.0.0.1` and we don't expose its port
(`8888`) through the UFW firewall or the cloud environment network
policies. It should be safe to allow connections from the server's own
IPv4 address and testing confirms this does fix the access denied errors
from TinyProxy.
=> Configure TinyProxy to allow connections from server IP.

tests/development-setup.yml
LXC image fingerprints appear to change often.
This PR fetches the latest fingerprint for Ubuntu Xenial/amd64 and used to pull in the correct image.
=> Fix CI (again)

playbooks/roles/openvpn/templates/instructions.md.j2
I just noticed on Ubuntu 17.10, when setting up OpenVPN, it was missing a 'Mode' setting under 'Additional TLS authentication or encryption'. As a result I pulled the file, added the line instructing the user to select TLS-Auth for their mode (that is the only viable option) and have submitted a pull request.
I checked to make sure there wasn't already an existing issue or pull request, so I apologize if I missed it. Let me know if you need screenshots or anything else for confirmation.
**As a side note, I'm noticing that Travis CI is failing this, and other pull requests because of a missing file at https://images.linuxcontainers.org/1.0/images/ubuntu%2Fxenial%2Famd64. If someone could fix that, that would be great :)**
=> Added the 'Mode' setting under 'Additional TLS Auth' settings for OpenVpn for Ubuntu 17.10

playbooks/roles/streisand-gateway/templates/instructions.md.j2
Firefox changed its settings menu in version 57. This just updates the instructions in the generated doc for importing the certificate.
I've tried this method with Firefox 57.0.2 on Windows 10 and Windows 7.
=> Update instructions for Firefox certificate import

README-chs.md, README-ru.md, README.md, requirements.txt
The French README already had this change, but instead of installing "apache-libcloud>=1.5.0", the user should install a version greater than 1.17.0. Although using the >=1.5.0 function will install apache-libcloud 2.2.1, it seemed better for both the sake of consistency and to avoid any bugs to ensure that the installed version is above the specified minimum in Ansible for use with Google's JSON credentials, which Streisand uses.
Look here for Ansible's documentation:
http://docs.ansible.com/ansible/latest/gce_module.html
=> fixing inconsistency in apache-libcloud requirement for GCE

playbooks/roles/shadowsocks/vars/main.yml
Upstream developers have updated the `shadowsocks-libev` version from `3.1.1` to `3.1.2`. [Changelog](https://github.com/shadowsocks/shadowsocks-libev/blob/master/debian/changelog) can be accessed here.
=> Update ss-libev from tag: 3.1.1 to 3.1.2

tests/development-setup.yml, tests/run.yml, tests/tests.sh
The upstream LXD project has deprecated the PPA we were using to get
a modern LXD/LXC version installed in Travis' super crusty 14.04
instances. The official recommendation is to either: A) use the old
packaged version in 14.04 or B) install a new version using `snap`.
Since we rely on network features not available in the 14.04 packaged
LXD this commit adopts the Snap approach (thanks to @alimakki for
originally starting on this!).
The primary changes involve configuring everything with a non-standard
LXD UNIX domain socket location.
Resolves https://github.com/StreisandEffect/streisand/issues/1150
=> Remove deprecated LXD PPA, use snap to install LXD.

playbooks/roles/openvpn/templates/instructions.md.j2
This may be a little nit-picky but I noticed that some of the wording is off for installing OpenVPN on Ubuntu. I think some changes were made in 17.10 and now things are laid out a little differently.
I made 2 changes to the instructions. First, Instead of telling the user to check a box (it no longer exists), I mentioned that they should view a particular section (so they can update that information).
Second, there is no 'Save' button anymore, it is now referred to as 'Add'. I've linked some screenshots below.
[No Check Box](http://frichetten.com/images/z-9.png)
[No Save Button](http://frichetten.com/images/z-10.png)
If this looks like a repeat, it is. This was originally Pull Request #1149 . I wanted to make a quick fix so I did it on my Master branch. After that, I found something …
=> Updated Wording for OpenVPN - Ubuntu for Ubuntu 17.10 (Fixed)

README.md
Added clarifying information in the README in regards to SSH keys. This was requested under Issue #1138. 
I'm happy to discuss ways for this to be improved! My primary goal was to explain a basic synopsis of what SSH keys are for, how to check if you have one, and mention that you can use a custom one when customizing your streisand instance.
=> Updated README to Clarify Information Regarding SSH Keys

README-chs.md, README-fr.md, README-ru.md, README.md
**Both** `boto` and `boto3` are required to provision an AWS instance
using the libraries/Ansible version shipped in master.
`requirements.txt` has already been updated, the individual READMEs
should be updated as well.
This supersedes https://github.com/StreisandEffect/streisand/pull/1126 Thanks to @taqtiqa-admin for flagging the
issue initially.
=> Add `boto3` to AWS requirements in READMEs.

playbooks/roles/sysctl/vars/main.yml
Explicitly set `fs.protected_hardlinks` and `fs.protected_symlinks` sysctl values to enabled.
Edit: tested on a vagrant e2e run.
=> Harden links

playbooks/roles/streisand-gateway/templates/vhost.j2
"HSTS diables..." -> "HSTS disables"
=> Fix typo in vhost.j2

playbooks/lets-encrypt.yml
- Allow LE role to run when no email is provided
- Update copy to reflect this but emphasise desirability
=> Make LE email address optional

playbooks/roles/ssh-forward/templates/instructions-fr.md.j2, playbooks/roles/ssh-forward/templates/instructions.md.j2
Without using `IdentitiesOnly yes` ssh client tries all the identity files in alphabetical order like following
```
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: /Users/kyslik/.ssh/bitbucket_rsa (0x7f930a5005e0),
debug2: key: do_vpn_forward_rsa (0x7f930a415eb0), explicit
debug2: key: /Users/kyslik/.ssh/do_vpn_forward_rsa (0x7f930a415ee0), explicit
debug1: Authentications that can continue: publickey
debug3: start over, passed a different list publickey
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /Users/kyslik/.ssh/bitbucket_rsa
debug3: send_pubkey_test …
```
=> Update ssh config docs to include `IdentitiesOnly`.

playbooks/roles/gce-network/tasks/main.yml
Prior to this commit the GCP stunnel firewall rule was created under the
same name as the OpenVPN firewall rule. This would stomp the OpenVPN
ports when stunnel was enabled. This commit uses a distinct name for the
stunnel firewall rule so that both it and the base OpenVPN rule can
coexist.
I verified that without this commit, I see the problem described in #1182. With 
this commit the correct rules are added.
Resolves https://github.com/StreisandEffect/streisand/issues/1182
=> GCP: Use distinct name for stunnel firewall rule

playbooks/roles/l2tp-ipsec/vars/main.yml
Changelog: https://download.libreswan.org/CHANGES
```
v3.23 (January 25, 2018)
* IKEv2: MOBIKE support (RFC 45555) [Antony/Paul]
* IKEv2: Add support for modecfgdns= and modecfgdomains= like for IKEv1 [Paul]
* IKEv2: EXPERIMENTAL: Support for Postquantim Preshared Keys [Vukasin Karadzic]
based on draft-ietf-ipsecme-qr-ikev2-01 (using private use numbers)
new option: ppk=yes|no|insist (default no)
* pluto: Fix DEFAULT_RUNDIR to be set so it is really configurable [Tuomo]
* pluto: Add support IDr payload (You Tarzan, me Jane) [Paul]
* pluto: pass state to send_crypto_helper_request() [Andrew]
* pluto: Internal time/scheduling changes, micro-seconds logging [Andrew]
* pluto: make counts of states consistently "unsigned" [Hugh]
* pluto/lib: Remove obsoleted/unused %myid support [Paul]
* …
```
=> Update LibreSwan to v3.23

README-chs.md, README-fr.md, README-ru.md, README.md
This commit removes the `area51.threeletter.agency` gitlab mirror.
I have to retire the box I'm running this on. I'll set up a new mirror
once I have finished migrating some systems around.
=> Remove area51 mirror from READMEs.

README-fr.md, playbooks/roles/l2tp-ipsec/templates/instructions-fr.md.j2, playbooks/roles/openconnect/templates/instructions-fr.md.j2, playbooks/roles/openvpn/templates/instructions-fr.md.j2, playbooks/roles/openvpn/templates/stunnel-instructions-fr.md.j2, playbooks/roles/shadowsocks/templates/instructions-fr.md.j2, playbooks/roles/ssh-forward/templates/instructions-fr.md.j2, playbooks/roles/streisand-gateway/templates/instructions-fr.md.j2, playbooks/roles/tor-bridge/templates/instructions-fr.md.j2
I just rename all ```Androïde``` to ```Android``` (s/Androïde/Android), because it's a brand.
With this commit, #1195 keeps consistency.
=> Change Androïde to Android

README-chs.md, README-fr.md, README-ru.md, README.md
Unfortunately, http://www.thekelleys.org.uk/ had no https alternative
Some URLs now redirect to different ones. For example:
http://www.infradead.org/ocserv/index.html redirected to https://ocserv.gitlab.io/www/index.html
=> Update README to use https

playbooks/roles/certificates/tasks/pkcs.yml, playbooks/roles/openconnect/tasks/docs.yml, playbooks/roles/openconnect/tasks/main.yml
The `certificates` role currently places the generated p12 and p12 password files within the vpn root directory, rather than their respective client directory.
This PR addresses this issue, as well as making the necessary modifications in the `ocserv` docs tasks to work properly (`ocserv` is the only vpn role that currently makes use of p12 files).
Tested on DO droplet with no issues.
=> Clean up pkcs12 locations 

playbooks/roles/shadowsocks/vars/main.yml
Upstreamed `SS-libev` to `3.1.3`. [Changelog](https://github.com/shadowsocks/shadowsocks-libev/blob/master/debian/changelog) here.
=> Upstreamed SS-libev to 3.1.3

streisand
This seems to work on bare macOS 10.13, and should resolve #1208.
BTW, I'm inclined to recommend `sudo python -m ensurepip` as the way to get pip on bare macOS.
=> One more place python2 -> python2.7 matters

playbooks/roles/sslh/tasks/main.yml
This commit updates the `sslh` playbook to edit the upstream `/lib/systemd/system/sslh.service` to set `StandardOutput=null`.
Without this change `sslh` will log client IPs to journald for all of the `:443` connections it multiplexes. We can't turn down the log level without upgrading to `sslh` version `1.18`+, and Ubuntu 16.04 only ships `1.17-2`.
As a short-term workaround this commit will write the output to `/dev/null`. This will make it harder to debug `sslh` related problems but will be a win for privacy.
I'd welcome any improvements for more intelligent filtering. It's a bit of a pain in the butt to pipe things through sed in a systemd world.
Resolves https://github.com/StreisandEffect/streisand/issues/1218
=> sslh: send stdout to null instead of journald

playbooks/roles/shadowsocks/tasks/main.yml, playbooks/roles/shadowsocks/vars/main.yml
This commit replaces the Ansible code that built `shadowsocks-libev`
from source with code to add an upstream PPA. This will ensure that
security updates are installed automatically and will speed up server
provisioning.
The build dependencies are still installed because `simple-obfs` is
being built from source (it is not presently available in an upstream
PPA). It's likely that this is installing more packages than are
required to build only `simple-obfs` but my hope is in the near future
it will be replaced by PPA install as well.
Prior to this commit Streisand instances ran `shadowsocks-libev` 
version `3.1.3`. This is still the case when installing from PPA.
Resolves https://github.com/StreisandEffect/streisand/issues/1221
=> shadowsocks: install shadowsocks-libev from PPA.

playbooks/roles/openvpn/templates/etc_openvpn_server.conf.j2, playbooks/roles/openvpn/templates/etc_openvpn_server_common.j2, playbooks/roles/openvpn/templates/etc_openvpn_server_udp.conf.j2, playbooks/roles/openvpn/vars/main.yml
I spent some time in the `openvpn` man page today so here are some small Streisand OpenVPN improvements this commit brings:
* Makes the `keepalive` configurable based on a playbook var
* Lowers the default keepalive interval and timeouts: Previously the OpenVPN connection would have to be broken for about an hour before it would be automatically restarted from the client side (and about two hours on the server side!). This commit applies the OpenVPN recommended values and the  connection should be restarted client-side after ~1m. It should be easier to lower/raise this in the future based on battery life/connectivity trade-off if required.
* Adds `mute 3` to the server config: why not :-)
* Adds `mlock` to the server config: this should be a very small security improvement.
* Adds …
=> OpenVPN: Configurable keepalives, server config comments.

tests/development-setup.yml
This commit adds explicit `snap connect` invocations for `lxd:lxd-support` and `lxd:lxd-network`. Without these the LXD snap services fail to start and CI stalls waiting for the LXD socket to become available.
I admit to not understanding _why_ these commands are required, or exactly what "snap plugs" are. Computers are a hot mess :-(
I discovered this workaround after finding https://bugs.launchpad.net/snapd/+bug/1657252 which leads me to believe this is a bug in the upstream `snapd` package.
As one definitive data point, changing out the LXD snap from the recently released `3.0.0` to the `2.0/stable` release channel did not fix the problem observed in CI.
Resolves https://github.com/StreisandEffect/streisand/issues/1252
=> CI: Explicitly connect LXD snap plugs.

playbooks/customize.yml, streisand
Make customizing the install a default action, answering `no` will read from the defined site-vars.
Resolves #1225
=> Always customize installation

playbooks/roles/ssh-forward/templates/instructions.md.j2
Looks like it was removed accidentally.
=> bring back setting permissions to ssh key

playbooks/roles/monit/templates/monitrc.j2
The bundled ssh.service systemd unit is already set to restart on failure allowing us to safely remove monit's ssh monitor.
Bundled ssh.service:
```
[Unit]
Description=OpenBSD Secure Shell server
After=network.target auditd.service
ConditionPathExists=!/etc/ssh/sshd_not_to_be_run
[Service]
EnvironmentFile=-/etc/default/ssh
ExecStart=/usr/sbin/sshd -D $SSHD_OPTS
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-failure
RestartPreventExitStatus=255
Type=notify
[Install]
WantedBy=multi-user.target
Alias=sshd.service
```
=> Remove SSH service monitor from monitrc

playbooks/roles/monit/templates/monitrc.j2, playbooks/roles/sslh/handlers/main.yml, playbooks/roles/sslh/tasks/main.yml, playbooks/roles/sslh/templates/sslh.cfg.j2, playbooks/roles/sslh/templates/sslh.service.j2, playbooks/roles/sslh/vars/main.yml
- create an sslh systemd drop-in file
- move `StandardOutput=null` to drop-in
- use a variable for sslh pid file
- remove sslh monitor from monitrc
=> Remove sslh monitor from monit

requirements.txt
Ansible 2.5.1 appears to be broken for us. 2.5.2 looks like it will have a fix. Pin to version 2.5.0 until then.
The SecretStorage module was just bumped to 3.0.0, and now requires Python 3. Until we're ready for Python 3, specify the earlier rev.
GCE requires pycrypto for authentication now.
=> Temporary pins of Ansible, SecretStorage versions; add pycrypto

playbooks/roles/ssh-forward/templates/instructions-fr.md.j2, playbooks/roles/ssh-forward/templates/instructions.md.j2
As per [issue 1284](https://github.com/StreisandEffect/streisand/issues/1284), a flag for verbose output is added to the SSH port-forwarding command which a user is instructed to run. This allows for verifying fingerprints without branching instructions for different users.
In addition, the French instructions lacked the `-N` flag for the same command, which has been added.
=> Add `-v` flag to user instructions for SSH port forwarding

playbooks/roles/download-and-verify/tasks/main.yml, playbooks/roles/gpg/tasks/main.yml, playbooks/roles/gpg/vars/main.yml
A user provisioning Streisand on Azure [reports a persistent failure](https://github.com/StreisandEffect/streisand/issues/1308#issue-318237314) during the Streisand GPG keyring import task with the following error msg:
> "gpg: can't connect to the agent: IPC connect call failed"
This is (likely?) caused by the gpg-agent not having started by the time we import the keys. I can't reproduce the bug myself so this may be a red herring.
This PR changes the gpg playbook to explicitly start both the gpg-agent and the dirnmgr instead of letting the first gpg operation do so. This PR also adds an explicit `wait_for` task for both the dirnmgr and gpg agent control sockets to make sure we don't proceed until both daemons are available.
The download-and-verify playbook invokes `gpg2` to check GPG …
=> GPG: explicitly wait for dirmngr and gpg-agent sockets.

README-chs.md, README-fr.md, README-ru.md, README.md
Okay, I know this is a really weird PR. But for a while now It has bugged me that the Streisand logo in the Readme was not centered. It is aligned to the left. Feel free to reject this PR but GitHub supports HTML in MD files so I just centered the image. I also retained the alt text if that is a requirement
Before:
After:
Additionally, if you want to see a live render of it visit https://github.com/Frichetten/streisand/tree/center_readme_logo which should be my branch with this change.
=> Center the Streisand logo in the Readme

.travis.yml, playbooks/roles/validation/tasks/ssh.yml, requirements.txt, tests/run.yml, util/ansible_check.sh
Raise the minimum version of Ansible to v2.5.2, will likely allow #1229 to be merged afterwards.
Resolves #1276
=> Bump Ansible CI to v2.5.2

playbooks/amazon.yml
Update EC2 regions and use order according to:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regions
The default region (Singapore) was maintained.
=> Update EC2 regions

streisand
Use "localhost" instead. I got confused and thought there was a cloud provider called "Localhost" so I selected option 8 (Existing Server) when I should have selected option 7.  Everyone is used to seeing localhost when referring to localhost. Localhost with a capital L is a proper name.
=> Change "Localhost" to "localhost"

playbooks/roles/common/tasks/main.yml
A trivial typo, the correct file name is "20auto-upgrades", source: https://help.ubuntu.com/community/AutomaticSecurityUpdates
=> Fix auto-upgrades config file name

playbooks/roles/test-client/tasks/wireguard-profiletest.yml, playbooks/roles/test-client/tasks/wireguard.yml, playbooks/roles/test-client/vars/main.yml, playbooks/roles/wireguard/tasks/docs.yml, playbooks/roles/wireguard/tasks/main.yml, playbooks/roles/wireguard/templates/instructions-fr.md.j2, playbooks/roles/wireguard/templates/instructions.md.j2
This had with it a few problems. Some versions of android don't like
config files with a dot in them, it would increase the length of the
interface beyond what it should be, and generally this belies the real
architecture of wireguard. Instead, call test interfaces and the server
interfaces 'wg0' and call each client interface by its profile name
alone.
While we're at it, we clean up the instructions a bit.
----------
This commit is entirely untested.
=> wireguard: remove awkward client/server notation

tests/development-setup.yml
In CI the `tests/development-setup.yml` tasks eventually run `lxc network attach-profile testbr0 default eth0`. Recently this has errored because `eth0` already exists. In the process of debugging I noticed things Just Work (TM) if this `attach-profile` step is skipped entirely.
This commit removes the `lxc network attach-profile` command from `test/development-setup.yml` and CI stops failing.
=> CI: Remove explicit LXC network profile attach.

requirements.txt
GCE appears to work with Ansible 2.5.4, which hasn't been true for several versions.
pycurl from PyPI now requires lots of fiddling and compile-time dependencies. Temporarily disable it in `requirements.txt` to keep it from breaking everyone else.
=> Ansible 2.5.4 works OK; roll back pycurl version

playbooks/roles/wireguard/tasks/main.yml
Related to WireGuard not fully upgraded on the fly #1374
=> Added .reload-module-on-update to make wireguard upgrades fully unattended

playbooks/roles/wireguard/templates/instructions.md.j2
Added instructions to install wireguard client for macOS.
client still experimental, but seems to be working.  A bit unstable yet.
=> Wireguard Cient installation instructions for macOS

playbooks/roles/wireguard/tasks/docs.yml, playbooks/roles/wireguard/tasks/main.yml, playbooks/roles/wireguard/templates/client-openwrt.txt.j2, playbooks/roles/wireguard/templates/instructions.md.j2, tests/development-setup.yml
There's been some interest in OpenWrt/LEDE support for WireGuard. This adds profiles and full (?) documentation. Works on OpenWrt devices from LEDE 17.01.4 and newer.
=> Generate OpenWrt WireGuard profiles and instructions

playbooks/roles/gpg/tasks/main.yml
@hamidzr wrote #1335, which fixes #1333, a case of a running `gpg-agent` not picking up changes from GPG configuration. When testing, I noticed the configuration issue affects `dirmngr` as well. If there's a running `dirmngr`, provisioning fails when trying to update the keyring. This patch addresses both components.
`dirmngr` doesn't seem respond to HUP or `--reload`, so it needs to be killed and restarted.
=> Add dirmngr to @hamidzr's gpg-agent patch in #1335

documentation/AWS.md
Hello!
In the suggested AWS IAM policy in the documentation, both `"ec2:DescribeAlarms"` and `"cloudwatch:DescribeAlarms"` are included. `"ec2:DescribeAlarms"` generates an error in IAM as the `DescribeAlarms` action doesn't exist for `ec2`. From some research, it seems like this was probably just included as a mistake.
Thank you! Keep up the great work, I rely on this project and appreciate all you do.
=> Remove "ec2:DescribeAlarms" from suggested IAM policy

playbooks/roles/lets-encrypt/tasks/install.yml, playbooks/roles/nginx/tasks/main.yml, playbooks/roles/openvpn/tasks/install.yml, playbooks/roles/tor-bridge/tasks/main.yml
This is mostly for the 200-line Tor key, but the other (25-line) keys were hidden for consistency.
=> Don't print long apt keys to the log

playbooks/roles/stunnel/vars/mirror.yml
The documentation at ```https://vpn.example.org/mirror/stunnel/index.html``` points to 
```https://vpn.example.org/mirror/stunnel/stunnel-latest-win32-installer.exe``` for the Windows
installer. 
The downloaded file however is named ```stunnel-latest-installer.exe```:
```
root@test6-localhost:/var/www/streisand/mirror/stunnel# pwd
/var/www/streisand/mirror/stunnel
root@test6-localhost:/var/www/streisand/mirror/stunnel# ls -l
total 3784
-rwxr-x--- 1 www-data www-data    6367 Aug  9 15:08 index-fr.html
-rwxr-x--- 1 www-data www-data     414 Aug  9 15:08 index-fr.md
-rwxr-x--- 1 www-data www-data    6367 Aug  9 15:08 index.html
-rwxr-x--- 1 www-data www-data     414 Aug  9 15:08 index.md
-rwxr-x--- 1 www-data www-data 3130792 Aug  9 15:08 stunnel-latest-installer.exe
-rwxr-x--- 1 www-data …
```
=> Fix stunnel windows mirror download location

playbooks/roles/common/tasks/detect-public-ip.yml, playbooks/roles/common/tasks/set-default-variables.yml
Challenge: Streisand VPN services not reachable due to external IP not visible on streisand-host for non-identified VM/host/cloud providers
Solution: Compare external and host IP address and update streisand_ipv4_address if neccessary
This will allow installation of streisand VPNs on a larger range of cloud providers. The challenge was discovered when installing streisand on a [Scaleway](https://www.scaleway.com/) 1-XS instances.
=> Add detection of public IP addresses for localhost and existing-server genesis

global_vars/default-site.yml, global_vars/integration/test-site.yml, global_vars/noninteractive/amazon-site.yml, global_vars/noninteractive/azure-site.yml, global_vars/noninteractive/digitalocean-site.yml, global_vars/noninteractive/google-site.yml, global_vars/noninteractive/linode-site.yml, global_vars/noninteractive/local-site.yml, global_vars/noninteractive/rackspace-site.yml, playbooks/customize.yml
https://www.torproject.org/docs/debian.html.en says to install the deb.torproject.org-keyring package. Here's what happens:
```
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
deb.torproject.org-keyring
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 4922 B of archives.
After this operation, 22.5 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
deb.torproject.org-keyring
```
Until we get enough time to figure this out, or upstream fixes it, disable the Tor bridge.
Resolves #1438.
=> Tor upstream is broken; disable it by default

playbooks/linode.yml
* The Linode Ansible module uses the now deprecated Linode APIv3. APIv3 keys can still be generated from the page specified: https://manager.linode.com/profile/api , however, users of the beta Linode Manager (https://cloud.linode.com) may be unaware of the incompatibility of APIv4 tokens and Streisand. (https://github.com/StreisandEffect/streisand/issues/1449).  This PR adds a note to help avoid confusion.
=> Note Incompatible API keys from Linode Cloud Manager

playbooks/roles/sslh/tasks/main.yml
`sslh` now `Recommends: apache2 | httpd, openssh-server | ssh-server` and so it picks up `apache2`. This breaks the `acmetool` redirector, since it wants to be on 80 too. Let's not install those recommendations. We should consider turning off Recommendations system-wide.
Resolves #1329 (already resolved?). Resolves #1349. Resolves #1459.
=> sslh Recommends apache2, which breaks acmetool redirector

playbooks/provider-detect.yml, playbooks/roles/common/tasks/detect-public-ip.yml, playbooks/roles/common/tasks/main.yml, playbooks/roles/dnsmasq/tasks/main.yml, playbooks/roles/gpg/tasks/main.yml, playbooks/roles/lets-encrypt/tasks/install.yml, playbooks/roles/nginx/tasks/main.yml, playbooks/roles/openconnect/tasks/install.yml, playbooks/roles/openvpn/tasks/install.yml, playbooks/roles/shadowsocks/tasks/main.yml, playbooks/roles/ssh-forward/tasks/docs.yml, playbooks/roles/sslh/tasks/main.yml, playbooks/roles/streisand-gateway/tasks/main.yml, playbooks/roles/stunnel/tasks/main.yml, playbooks/roles/test-client/tasks/shadowsocks.yml, playbooks/roles/test-client/tasks/stunnel.yml, playbooks/roles/test-client/tasks/tor.yml, playbooks/roles/tinyproxy/tasks/main.yml, playbooks/roles/tor-bridge/tasks/main.yml, playbooks/roles/ufw/tasks/main.yml, playbooks/roles/wireguard/tasks/install.yml, tests/development-setup.yml, tests/run.yml
I've unilaterally decided that `apt:` stanzas shall consistently use `package:` rather than `name:`.
https://docs.ansible.com/ansible/2.5/modules/apt_module.html#apt-module says that "When used with a loop: each package will be processed individually" and suggests directly feeding a list to `apt:`.
=> "apt:" stanza package reform

playbooks/roles/stunnel/tasks/main.yml
Doing so will fail in re-running the the script on an already spun up server.
Resolves #1454
=> Do not delete stunnel's init.d service

playbooks/roles/wireguard/templates/instructions.md.j2
This PR was made in response to Issue #1434 . Ubuntu/Debian users will need to use the openresolv package in order to run Wireguard as noted [here](https://lists.zx2c4.com/pipermail/wireguard/2017-May/001351.html) and [here](https://mullvad.net/en/guides/wireguard-and-mullvad-vpn/).
The fix is simple for the user, just install openresolv and Wireguard will be able to use it.
(Had to resubmit this PR due to the GitHub outage issues)
=> Updated documentation to fix issue found in Issue #1434

playbooks/roles/openvpn/templates/instructions.md.j2
The Streisand OpenVPN configuration uses network-manager-openvpn-gnome as a nice plugin. Due to some minor variances between the different Ubuntu versions we have slight instruction changes between them. I have tested Ubuntu 18.10 and confirmed that it is the same as 18.04. This Pull Request is just updating the documentation to reflect that.
=> 18.10 openvpn doc update

playbooks/azure.yml, playbooks/roles/genesis-azure/defaults/main.yml
Noticed France along with the new Austrailia regions were missing. Added those. 
Additionally, Microsoft is working to deprecate the Basic_A0 VM type (they currently oversubscribe those), and it's currently $14 USD globally as opposed to the newer Standard_B1s, which has more CPU and RAM headroom for less (~$7 USD depending on region).
=> Add new Azure regions and update azure_instance_type to newer generation

playbooks/roles/ssh-forward/templates/instructions.md.j2
I think a majority of Streisand SSH users are on 80/443-only networks. It doesn't hurt much if people who do have 22 open use 443 instead. Switch instructions/code blocks to 443, and tell people, "by the way, port 22 works."
Requires update of fr documentation.
=> Switch SSH instructions to port 443, offer 22 if user wants to try it

README-fr.md, README-ru.md, README.md, playbooks/roles/openconnect/templates/instructions.md.j2
Also yum -> dnf for Fedora instructions (yum is gone in Fedora for a while now)
=>  Fix typo: certifcate -> certificate

playbooks/roles/wireguard/templates/instructions.md.j2
Closes #1500. 
I only use Streisand once in a while, and so I haven't verified that these instructions display correctly.
=> Add WireGuard instructions for iOS.

.travis.yml
Workaround for  [no public key available](https://travis-ci.community/t/then-sudo-apt-get-update-failed-public-key-is-not-available-no-pubkey-6b05f25d762e3157-in-ubuntu-xenial/1728) travis CI errors
=> Fix Travis CI builds "public key is not available"

playbooks/roles/common/vars/main.yml
While I was working on getting Streisand to run inside a Docker container, I noticed that this package was out of date (and thus causing Streisand to error out). I have updated it and re-tested it. (My first commit I got the name of the package wrong. It was fixed in the second, and then tested).
This is the error I was getting from Streisand:
This is what happens when you try to install the outdated package with apt. It recommends the newer one.
Here is a [link](https://bugs.launchpad.net/ubuntu/+source/ubuntu-meta/+bug/439566) to another source recommending the newer package.
=> Updated the 'python-software-properties' package to 'software-properties-common'.

requirements.txt
Work on `pycrypto` [stopped in 2013](https://pypi.org/project/pycrypto/#history). It looks like [pycryptodome](https://www.pycryptodome.org/en/latest/src/vs_pycrypto.html) is compatible. Tested with deployment to GCE (our declared requirement for `pycrypto`).
=> pycrypto will not build on (at least) macOS 10.14; upgrade to pycryptodome

Installation.md
There was a small error causing styles in last section to be messed up a little bit
=> Small documentation fix caused by block quotes

playbooks/roles/tor-bridge/tasks/main.yml, playbooks/roles/tor-bridge/tasks/mirror-common.yml
This PR changes the apt_key mechanism to pull the GPG key from deb.torproject.org and also fixes the URL used to retrieve TBB version info.
=> fix tor install

playbooks/roles/wireguard/templates/client.conf.j2
Adding "::/0" to AllowedIPs on clients to route all IPv6 traffic through the Wireguard tunnel in addition to IPv4 traffic
=> Wireguard: prevent ipv6 leaks on clients

tests/site_vars/random.yml
CI "random" was blowing up when shadowsocks got selected, because the variable `streisand_shadowsocks_v2ray_enabled` was undefined. Include it as one of the randomized options.
=> CI fix: define v2ray as a randomizable option

requirements.txt
This should fix the error seen when creating a new network in GCP (inside the `gce-network: Create network` task) when running Streisand for the first time. Error message below (originally reported in #1623):
> TASK [gce-network : Create network] ********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "libcloud with GCE support (0.17.0+) required for this module"}
Apparently `apache-libcloud` is a requirement for the `gce_net` module in Ansible, which is being used inside this playbook:
https://github.com/StreisandEffect/streisand/blob/master/playbooks/roles/gce-network/tasks/main.yml#L3
The error message seems to come from this file within Ansible:
https://github.com/ansible/ansible/blob/v2.8.0/lib/ansible/modules/cloud/google/gce_ …
=> Fix libcloud requirement error on GCP builds (#1623)

README-chs.md, README-ru.md, playbooks/roles/genesis-digitalocean/tasks/main.yml, requirements.txt
PR to upgrade the `digital_ocean` Ansible module to use the newer `digital_ocean_droplet` and `digital_ocean_sshkey` modules.
See deprecation notice here for `digital_ocean` (will be removed in Ansible 2.12):
https://docs.ansible.com/ansible/latest/modules/digital_ocean_module.html#deprecated
Not sure if Streisand will be upgrading to Ansible 2.12 anytime soon, but I figured it couldn't hurt since it was a pretty easy upgrade (the syntax is very similar). It has the added benefit of removing an external dependency on the python module `dopy` (not that I have anything against it :). Tested against digitalocean and seems to work well without `dopy` installed into the virtualenv.
=> Upgrade digitalocean module

.travis.yml, ansible.cfg, library/digital_ocean_droplet.py, playbooks/roles/genesis-digitalocean/tasks/main.yml, requirements.txt, util/ansible_check.sh
The dopy module, which is what's behind the `digital_ocean` Ansible module, has multiple issues with DigitalOcean API changes. It's also deprecated and depends on Python 2.7.
Fortunately, `digital_ocean_droplet` and friends were added to Ansible to replace `digital_ocean`.
Unfortunately, `digital_ocean_droplet` was recently broken by DO. Our friends at Algo ran into this too (https://github.com/trailofbits/algo/issues/1571), and filed a PR against Ansible. Their proposed module is now in the `library` directory. We'll remove it when Ansible fixes `digital_ocean_droplet`.
Finally, we upgrade to Ansible 2.8.4.
=> Update to digital_ocean_droplet module; vendor Algo's patched version

playbooks/roles/genesis-amazon/tasks/main.yml, requirements.txt
If the user has specified a VPC to launch into, we can clearly use `assign_public_ip: true`. But if the VPC is undefined, we shouldn't specify this. And apparently `assign_public_ip: false` is not good enough; we need to *omit* the clause.
Fixes #1509. Fixes #1499.
=> Fix AWS assign_public_ip crash

playbooks/customize.yml, playbooks/roles/shadowsocks/tasks/v2ray.yml, playbooks/roles/shadowsocks/vars/main.yml, tests/site_vars/shadowsocks.yml
See https://github.com/StreisandEffect/streisand/issues/1642
Under the hood, `go get` uses git to fetch upstream dependencies, so we just manually clone the v2ray/v2ray-core repo just before running `go get`. When the v2ray role runs the `go get` command, go will see that the v2ray/v2ray-core repo already exists in `GOPATH` and will skip fetching the repository, and no longer fail with the "insecure redirect" error.
This workaround ideally should be removed when either go releases a new version that ignores unsafe redirects, or Github Pages is able to fix the insecure redirect bug that exists for v2ray.com/core (see https://github.com/StreisandEffect/streisand/issues/1642#issuecomment-529265026)
Also, I figured it made sense to revert …
=> [Temporary] workaround for v2ray/core insecure redirect issue

playbooks/roles/lets-encrypt/files/01-reload-nginx.sh, playbooks/roles/lets-encrypt/tasks/main.yml
In testing the `lets-encrypt` role recently, I forced renewal for an existing cert (`certbot --force-renewal renew`) and realized nginx was still serving the old certificate, even though the renewal technically worked.
This PR fixes that by using a deploy hook (documented [here](https://certbot.eff.org/docs/using.html#renewing-certificates)), which runs after successful certificate renewals (not each attempt).
The deploy hook is simply a script that runs one command: `systemctl reload nginx`. Reloading nginx will cause it to start serving the new certificate, and gracefully shutdown old worker processes.
For posterity's sake, if anyone already deployed the certbot changes in [this PR](https://github.com/StreisandEffect/streisand/pull/1668), you can manually implement this fix if you don't …
=> Adds certbot deploy hook to reload nginx after cert renewal

Services.md
Current url for tinyproxy (https://banu.com/tinyproxy/) in docs does not work. Should be changed to https://tinyproxy.github.io/.
=> fix tinyproxy link in Services.md

playbooks/google.yml
Seems like HK zones opened in 2018. HK zone should be the best choice for many of users.
=> Add GCP East Asia (Hong Kong) zones

playbooks/roles/nginx/files/nginx.conf
See #1699 for an example of this.
nginx is not the most performance-critical piece of software in Streisand.
=> Bump up the size of nginx hashes; some people are running into size limits

playbooks/roles/shadowsocks/vars/mirror.yml
Very small change here, but I noticed the macOS and Windows mirrors are over 2 years old.
The latest version for macOS ([see here](https://github.com/shadowsocks/ShadowsocksX-NG/releases)) of Shadowsocks-NG (v1.9.4) has the v2ray-plugin built in which makes usage much much easier.
Also worth updating the Windows version ([see here](https://github.com/shadowsocks/shadowsocks-windows/releases)) at the same time’
Thanks!
=> Bump shadowsocks mirrored versions to latest

tests/development-setup.yml, util/ansible_check.sh, util/version_at_least.py
CI is blowing up because 2.8.10 of Ansible has been released, and "2.8.10" < "2.8.4". Write a tiny Python utility to do proper version comparisons.
=> Use a proper Ansible version comparison (because stringwise, 2.8.10<2.8.4)
