StreisandEffect/streisand

- playbooks/roles/streisand-gateway/templates/index.md.j2
Hi there. I added a bit more information on the streisand gateway page about the connection methods, and the list of mirrors. A common cause of confusion for my users is that they are not sure which method to pick, so I made that clearer.
This is a no-frills commit, so it should be easily mergeable.
> Improved connection list description

- library/gce.py
- playbooks/google.yml
- playbooks/roles/genesis-google/defaults/main.yml
- Adding latest gce.py
- Updating gce image with proper Ubuntu name.
- Resolving ntp conflict.
> Updating gce

- playbooks/roles/ufw/tasks/main.yml
- playbooks/streisand.yml
Hi,
I needed this for my server and wondered why it was not done already.  
Does using one of the supported cloud providers forbid configuring the firewall
automatically?
> Set firewall rules using ufw.

- playbooks/amazon.yml
- playbooks/roles/genesis-amazon/defaults/main.yml
- playbooks/roles/genesis-amazon/tasks/determine-ami-id.yml
Please verify the ami-id: I choose a more recent version of Ubuntu 14.04
> Added support for Amazon eu-central (Germany) region

- streisand
> fix ansible version check

- playbooks/roles/ssh/files/sshd_config
- playbooks/roles/ssh/tasks/main.yml
- Adding back in PAM.
- Ensure all host keys are generated
- Fixing sftp path.
- Fixes https://github.com/jlund/streisand/issues/292
> - Fixing mode permissions (when using new format, you need to add the 0)

- playbooks/digitalocean.yml
> added bangalore region for digital ocean

- playbooks/roles/streisand-mirror/vars/openvpn.yml
> Updated to the latest stable version of Tunnelblick v3.6.4a

- playbooks/amazon.yml
> Add Mumbai region (ap-south-1)

- playbooks/roles/streisand-mirror/vars/openvpn.yml
Updated tunnelbick to latest version, resolved  #409
> Tunnelblick

- playbooks/roles/common/vars/main.yml
Resolves  #418, tested on Scaleway VC1S instance
> Ensure AppArmor dependency

- playbooks/amazon.yml
AWS just added this region today. See https://aws.amazon.com/blogs/aws/now-open-aws-us-east-ohio-region/.
> [aws] Add us-east-2 region

- playbooks/linode.yml
According to this doc: https://www.linode.com/api/utility/avail.datacenters
> Added tokyo2 region for linode

- streisand
Some minor edits to the main provisioning script, checking whether ansible itself is installed before checking its version, feedback if the user get's the options wrong when selecting which provider, minor cleanup.
> More error checking in provisioning script

- playbooks/roles/streisand-mirror/vars/stunnel.yml
> Fix broken link for stunnel mirror (Fixes #493 )

- playbooks/roles/l2tp-ipsec/templates/ipsec.conf.j2
- playbooks/roles/l2tp-ipsec/vars/main.yml
Closes https://github.com/jlund/streisand/issues/514
This update does not include the changes to the `ike` or `phase2alg` as I'm not familiar with those. However I can add them to this PR.
> Libreswan 3.19 update

- playbooks/roles/openvpn/templates/client-combined.ovpn.j2
remove the option and it works fine
> issue #527 remove "--connect-timeout" for udp protocol in combined profile

- README.md
Changed two sentences around so it didn't sound as redundant.
> Remove redundancy in README

- README.md
- ansible.cfg
- playbooks/google.yml
- playbooks/roles/common/tasks/main.yml
- playbooks/roles/common/vars/main.yml
- playbooks/roles/gce-network/tasks/main.yml
- playbooks/roles/l2tp-ipsec/handlers/main.yml
When creating GCE network use auto instead of legacy mode
Update GCE doc url to use https
Bump minimum apache-libcloud version
Add retry logic to l2tp-ipsec handler
Update ansible.cfg with temporary workaround related to ansible/ansible#18894
Add system update task
> Misc updates/fixes

- playbooks/roles/streisand-mirror/vars/openvpn.yml
Tested on a DO droplet successfully.
Closes #600
> Updated OpenVPN mirror GPG signing keys

- README.md
- playbooks/roles/genesis-azure/tasks/main.yml
* Add Azure to the list of supported providers in the README.
* Place the pip segment in the README in alphabetical order.
* Convert two tasks to multi-line YAML syntax.
> Minor Azure cleanup

- documentation/AZURE.md
- playbooks/azure.yml
Added the missing step-by-step Azure credentials file setup.
> Azure setup documentation

- streisand
This patch cleans things up a bit and then dynamically figures out which python to use before launching ansible.
> Fix the python inventory situation

- README.md
> Fix indent in code blocks

- playbooks/roles/monit/templates/monitrc.j2
- playbooks/roles/streisand-gateway/templates/vhost.j2
fixes https://github.com/jlund/streisand/issues/585
> Add Streisand IP to Monit config

- README.md
- playbooks/roles/shadowsocks/templates/instructions.md.j2
- playbooks/roles/streisand-mirror/vars/shadowsocks.yml
* Modify the instructions for Shadowrocket on iOS.
* Update the README to reference the new AEAD functionality and modern
cipher support.
* Minor indentation fix.
> Shadowsocks updates

- playbooks/roles/openvpn/templates/instructions.md.j2
- playbooks/roles/streisand-mirror/vars/openvpn.yml
- Added NetwrokManager instructions to verify the x509 name 
- Removed unnecessary frontslash from `openvpn_base_download_url`
Edit: Tested on DO droplet, no issues. Closes #662
> Update OpenVPN instructions

- playbooks/roles/streisand-mirror/vars/openvpn.yml
Updates the mirrored version of Tunnelblick to v3.7.1.
Tested on DO with no issues.
> Tunnelblick update

- playbooks/google.yml
> Add Northern Virginia to GCE zones list

- streisand
> Restore SCRIPT_DIR

- README.md
This PR updates README.md to include the mentioning of 'simple-obfs' installation. Related to #741.
> Update README.md to mention 'simple-obfs' installation

- playbooks/google.yml
Added Australian regions/zones to google cloud playbook, closes #775
Fixed spelling Sinagapore -> Singapore
> Added Australia region to GCE per #775

- monkey/usercustomize.py
- playbooks/roles/test-client/files/shadowsocks-qr-decode.py
Ran flake8 against python scripts to conform them to python community standards. No new functionality added.
> Ran flake8 against python scripts

- playbooks/amazon.yml
- playbooks/azure.yml
- playbooks/cloud-status.yml
- playbooks/digitalocean.yml
- playbooks/existing-server.yml
- playbooks/google.yml
- playbooks/linode.yml
- playbooks/localhost.yml
- playbooks/provider-detect.yml
- playbooks/python.yml
- playbooks/rackspace.yml
- playbooks/roles/genesis-digitalocean/tasks/main.yml
- playbooks/roles/rsyslog/tasks/main.yml
- playbooks/roles/shadowsocks/tasks/simple-obfs.yml
- playbooks/roles/streisand-gateway/tasks/main.yml
- playbooks/roles/streisand-mirror/tasks/shadowsocks.yml
- playbooks/roles/test-client/tasks/main.yml
- playbooks/streisand.yml
- playbooks/test-client.yml
- playbooks/vagrant.yml
Ran yamllint and fixed all reported _errors_ . There's still plenty of warnings, but that probably warrants a stylistic discussion.
> Ran yamllint

- playbooks/azure.yml
> location 'southeastssia' is not available. it shall be southeastasia

- README-fr.md
- README.md
Somehow I messed up the world's smallest PR! (Twice!)
> Fix mirror URL

- README-fr.md
- README.md
- Add a Gitlab mirror
- Add build status for README-fr.md
> Streisand mirror

- playbooks/roles/openvpn/tasks/docs.yml
It looks like this task is a duplicate of the task with the same name on line 16.
> Remove a repeated documentation task in the OpenVPN role

- playbooks/roles/common/templates/languages.md.j2
- playbooks/roles/openvpn/templates/stunnel-instructions-fr.md.j2
- playbooks/roles/openvpn/templates/stunnel-instructions.md.j2
- playbooks/roles/streisand-gateway/templates/firewall-fr.md.j2
- playbooks/roles/streisand-gateway/templates/firewall.md.j2
- playbooks/roles/streisand-gateway/templates/index-fr.md.j2
- playbooks/roles/streisand-gateway/templates/index.md.j2
- playbooks/roles/streisand-gateway/templates/instructions-fr.md.j2
- playbooks/roles/streisand-gateway/templates/instructions.md.j2
> replace iteritems() -> items()

- playbooks/roles/wireguard/templates/instructions.md.j2
Thanks to @HougeLangley for submitting the documentation update in https://github.com/jlund/streisand/pull/858. I've created this PR to add one editorial commit in addition.
> Docs to enable Wireguard service on Systemd Linux Distros

- documentation/SOURCES.md
Can I get a sanity check on this approach?
> Lists source of all installed and mirrored packages, resolves #711

- playbooks/roles/shadowsocks/templates/instructions-fr.md.j2
- playbooks/roles/shadowsocks/templates/instructions.md.j2
See #856 for more details.
Note: this isn't a fix for the project, just a suggestion/notice to inform users.
> Add a note about Shadowrocket not being available in the China App Store

- playbooks/roles/shadowsocks/vars/mirror.yml
Resolves https://github.com/jlund/streisand/issues/864
> Update shadowsocks-android mirror to 4.2.2

- README-chs.md
- README.md
New Chinese Simplified README version is done
> Chinese Simplified README

- playbooks/roles/shadowsocks/vars/mirror.yml
Resolves https://github.com/jlund/streisand/issues/878
> Fix Shadowsocks Android mirror expected shasum format

- .gitignore
This is mostly a matter of taste; I can put these in a global ignore too. So NAK this at will.
> RFC: make gitignore better for emacs/OS X users

- playbooks/roles/shadowsocks/templates/instructions-fr.md.j2
- playbooks/roles/shadowsocks/templates/instructions.md.j2
minor updates for the shadowsocks instructions to clarify how to use simple-obfs (#893) and update the instructions adding a profile for the new Android UX (#909)
> Shadowsocks client documentation update

- playbooks/roles/openconnect/vars/mirror.yml
- updates OpenConnect GUI for windows to version 1.5.2
> Update OpenConnect mirror

- playbooks/roles/l2tp-ipsec/templates/instructions-fr.md.j2
- playbooks/roles/streisand-gateway/templates/instructions-fr.md.j2
- translated missing section for iOS
- resolves #938
> Update L2TP French translation

- README-chs.md
- README-fr.md
- README-ru.md
- Update Azure pip instructions from #940
- Language names written in native language in README-ru to be consistent
- Added mirror links in README-ru
> README updates

- documentation/localization_howto.md
As was suggested in the following [streisand-discussions topic](https://github.com/jlund/streisand-discussions/issues/43), this PR aims to document how one would approach localization efforts for Streisand.
> Localization How-to

- playbooks/roles/openvpn/vars/mirror.yml
- playbooks/roles/shadowsocks/vars/mirror.yml
- Updates tunnelblick to latest stable v3.7.2a
- Updates ShadowsocksX-NG to v1.6.1
Resolves #966, #964
> Client Updates

- README-fr.md
- sentimentally translate the updated README
> README-fr update

- playbooks/roles/lets-encrypt/vars/main.yml
Let's Encrypt has updated their agreements.
> lets-encrypt: Update agreements PDF

- playbooks/roles/l2tp-ipsec/templates/instructions.md.j2
Added instructions in the generated-docs template for adding L2TP/IPsec manually with Windows 10.
> added L2TP-IPsec instructions for adding to windows 10, manually

- README-chs.md
updating for changes from #1000  and #1045
> updated chinese translation

- playbooks/roles/openvpn/templates/instructions-fr.md.j2
l'accès aux -> l'accès au
merci @tiliarou
> Grammar corrections for OpenVPN fr instructions

- playbooks/roles/certificates/tasks/ca-server.yml
- playbooks/roles/certificates/tasks/pkcs.yml
- playbooks/roles/common/tasks/main.yml
- playbooks/roles/common/vars/main.yml
- playbooks/roles/l2tp-ipsec/tasks/main.yml
- playbooks/roles/openconnect/tasks/main.yml
- playbooks/roles/streisand-gateway/tasks/main.yml
- playbooks/roles/tor-bridge/tasks/main.yml
I've been meaning to do this for a while.
My rules:
- Things users type use dots, `.`
- Things that are filenames probably should use hyphens, `-`
- I like the way `-` (hyphen) looks when I don't have to type it.
I'm up for suggestions on key length, etc.
> Switch to BIP identifiers/password generation

- requirements.txt
Fix the ordering of the venv requirements to ensure the correct dependencies are installed
> Virtual environment requirements fix

- .travis.yml
See: https://docs.travis-ci.com/user/caching/#pip-cache
> Cache `pip` packages between CI runs.

- README.md
WireGuard is working pretty good within the PRC. I thought it was worth mentioning in the README.md file.
> A minor edit in README.md

- playbooks/roles/genesis-digitalocean/defaults/main.yml
Smallest droplet has 1GB now. Default of genesis-digitalocean adjusted.
> Update genesis-digitalocean for their new pricing

- README-fr.md
- playbooks/roles/openvpn/templates/instructions-fr.md.j2
- playbooks/roles/streisand-gateway/templates/instructions-fr.md.j2
- playbooks/roles/streisand-gateway/templates/instructions.md.j2
Resolves #1123, with a minor tweak to the Firefox gateway certificate import instructions English instructions.
> Update French localizations

- playbooks/roles/openvpn/templates/instructions-fr.md.j2
- playbooks/roles/openvpn/templates/stunnel-instructions-fr.md.j2
-  done on the file `instructions-fr.md.j2`
- done on the file `stunnel-instructions-fr.md.j2`
> [FRENCH] Minor correction

- README-fr.md
> Update README-fr 

- README-fr.md
> Chiffrer, not crypter

- playbooks/roles/openconnect/templates/mirror-fr.md.j2
- playbooks/roles/openconnect/templates/mirror.md.j2
- playbooks/roles/openconnect/vars/mirror.yml
> Mirror OpenConnect macOS client

- playbooks/roles/openvpn/templates/instructions-fr.md.j2
> Update OpenVPN fr instructions

- playbooks/roles/l2tp-ipsec/templates/instructions-fr.md.j2
- playbooks/roles/l2tp-ipsec/templates/instructions.md.j2
- playbooks/roles/openconnect/templates/instructions-fr.md.j2
- playbooks/roles/openconnect/templates/instructions.md.j2
- playbooks/roles/openvpn/templates/instructions-fr.md.j2
- playbooks/roles/openvpn/templates/instructions.md.j2
- playbooks/roles/openvpn/templates/stunnel-instructions-fr.md.j2
- playbooks/roles/openvpn/templates/stunnel-instructions.md.j2
- playbooks/roles/shadowsocks/templates/instructions-fr.md.j2
- playbooks/roles/shadowsocks/templates/instructions.md.j2
- playbooks/roles/ssh-forward/templates/instructions-fr.md.j2
- playbooks/roles/ssh-forward/templates/instructions.md.j2
- playbooks/roles/wireguard/templates/instructions-fr.md.j2
- playbooks/roles/wireguard/templates/instructions.md.j2
- updates generated French instructions to match #1241
- Google -> DuckDuckGo
> Update generated FR instructions

- playbooks/roles/common/templates/50unattended-upgrades.j2
Adds shadowsocks-libev to unattended upgrades
> Autoupdate shadowsocks

- documentation/AWS-fr.md
- documentation/AWS.md
> Update AWS policy document JSON

- documentation/localization_howto.md
One more place IPSec has hidden.
> update localization_howto to mirror IPSec removal

- documentation/localization_howto.md
fix path to main.yml in localization_howto
> fix path to main.yml in localization_howto

- playbooks/roles/shadowsocks/handlers/main.yml
- playbooks/roles/shadowsocks/tasks/main.yml
- playbooks/roles/shadowsocks/templates/shadowsocks-libev.service.j2
- playbooks/roles/shadowsocks/vars/main.yml
- explicitly sets `daemon_reload: yes`
- create a drop-in to restart on failure
Resolves #1247
> Ensure that shadowsocks-libev restarts after a reboot

- playbooks/roles/common/templates/50unattended-upgrades.j2
- add wireguard ppa to unattended-upgrades
> WireGuard unattended upgrades

- playbooks/roles/common/files/header.html
> [header.html] Prevent layout change on link hover

- playbooks/customize.yml
stunnel is related to OpenVPN, so the stunnel question should follow the OpenVPN question.
Since we're going to bounce people out in validation for selecting it without OpenVPN, be a little more stern in how we ask.
> Make more clear that you only want/only can have stunnel with OpenVPN

- playbooks/roles/openvpn/templates/instructions-fr.md.j2
- playbooks/roles/openvpn/templates/instructions.md.j2
> Clarify OpenVPN client certificate re-use

- CONTRIBUTING.md
> Fix CONTRIBUTING.md typo

- global_vars/noninteractive/google-site.yml
- playbooks/google.yml
Also adds support for named zones for robust noninteractive deployments. Otherwise it will break after every zone adddition, unless we do not sort the list...
> Adds gcp west europe netherlands

- playbooks/roles/openvpn/templates/instructions.md.j2
There have been some issues with versions of Ubuntu. See Issue #1296 for information about problems with 16.04. 16.10 and 17.04 are now end of life (see https://wiki.ubuntu.com/Releases). I have updated the documentation (minor changes) to reflect 17.10 and 18.04 which are currently supported. Going forward it may be a good idea to update these entries for each Ubuntu release (there are usually some minor changes).
> Updated Documentation for Ubtuntu 17.10, 18.04 and 16.04.

- playbooks/roles/openvpn/templates/instructions-fr.md.j2
- playbooks/roles/openvpn/templates/instructions.md.j2
- update fr instructions to reflect changes made in #1408
- correct instructions to mention LZ4 compression instead of LZO in en and fr docs (see #1310)
> Update OpenVPN instuctions

- global_vars/noninteractive/amazon-site.yml
region list has been changed in #1326
> update amazon ec2 region list in noninteractive config

- playbooks/roles/wireguard/templates/instructions.md.j2
> fix a symbol mistake

- .github/workflows/streisand.yml
- playbooks/roles/gpg/tasks/main.yml
- tests/yamllint-config.yml
Update Yarn Debian key (see https://github.com/yarnpkg/yarn/issues/7866)
> add Update Yarn Debian key in GitHub Actions
